/**
 * Juno
 * Juno Public API Docs
 *
 * The version of the OpenAPI document: 1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';

export class AccessKey {
  /**
   * Client public access key
   */
  'publicAccessKey': string;
  /**
   * Client private access key
   */
  'privateAccessKey': string;

  static discriminator: string | undefined = undefined;

  static attributeTypeMap: Array<{
    name: string;
    baseName: string;
    type: string;
  }> = [
    {
      name: 'publicAccessKey',
      baseName: 'publicAccessKey',
      type: 'string',
    },
    {
      name: 'privateAccessKey',
      baseName: 'privateAccessKey',
      type: 'string',
    },
  ];

  static getAttributeTypeMap() {
    return AccessKey.attributeTypeMap;
  }
}
