/**
 * Juno
 * Juno Public API Docs
 *
 * The version of the OpenAPI document: 1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';

export class AcceptAccountRequestResponseUser {
  /**
   * User ID
   */
  'id': number;
  /**
   * Email
   */
  'email': string;
  /**
   * Name
   */
  'name': string;
  /**
   * User type
   */
  'type': AcceptAccountRequestResponseUser.TypeEnum;
  /**
   * Project IDs the user is linked to
   */
  'projectIds'?: Array<number>;

  static discriminator: string | undefined = undefined;

  static attributeTypeMap: Array<{
    name: string;
    baseName: string;
    type: string;
  }> = [
    {
      name: 'id',
      baseName: 'id',
      type: 'number',
    },
    {
      name: 'email',
      baseName: 'email',
      type: 'string',
    },
    {
      name: 'name',
      baseName: 'name',
      type: 'string',
    },
    {
      name: 'type',
      baseName: 'type',
      type: 'AcceptAccountRequestResponseUser.TypeEnum',
    },
    {
      name: 'projectIds',
      baseName: 'projectIds',
      type: 'Array<number>',
    },
  ];

  static getAttributeTypeMap() {
    return AcceptAccountRequestResponseUser.attributeTypeMap;
  }
}

export namespace AcceptAccountRequestResponseUser {
  export enum TypeEnum {
    Superadmin = <any>'SUPERADMIN',
    Admin = <any>'ADMIN',
    User = <any>'USER',
  }
}
