/**
 * Juno
 * Juno Public API Docs
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';

export class AnalyticsConfigResponse {
    'id': number;
    'environment': string;
    'serverAnalyticsKey': string;
    'clientAnalyticsKey': string;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "id",
            "baseName": "id",
            "type": "number"
        },
        {
            "name": "environment",
            "baseName": "environment",
            "type": "string"
        },
        {
            "name": "serverAnalyticsKey",
            "baseName": "serverAnalyticsKey",
            "type": "string"
        },
        {
            "name": "clientAnalyticsKey",
            "baseName": "clientAnalyticsKey",
            "type": "string"
        }    ];

    static getAttributeTypeMap() {
        return AnalyticsConfigResponse.attributeTypeMap;
    }
}

