/**
 * Juno
 * Juno Public API Docs
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';

export class CustomEventResponse {
    /**
    * Event ID
    */
    'id': string;
    /**
    * Event type ID
    */
    'eventTypeId': string;
    /**
    * Project ID
    */
    'projectId': string;
    /**
    * Environment
    */
    'environment': string;
    /**
    * Created timestamp
    */
    'createdAt': string;
    /**
    * Updated timestamp
    */
    'updatedAt': string;
    /**
    * Custom properties
    */
    'properties': object;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "id",
            "baseName": "id",
            "type": "string"
        },
        {
            "name": "eventTypeId",
            "baseName": "eventTypeId",
            "type": "string"
        },
        {
            "name": "projectId",
            "baseName": "projectId",
            "type": "string"
        },
        {
            "name": "environment",
            "baseName": "environment",
            "type": "string"
        },
        {
            "name": "createdAt",
            "baseName": "createdAt",
            "type": "string"
        },
        {
            "name": "updatedAt",
            "baseName": "updatedAt",
            "type": "string"
        },
        {
            "name": "properties",
            "baseName": "properties",
            "type": "object"
        }    ];

    static getAttributeTypeMap() {
        return CustomEventResponse.attributeTypeMap;
    }
}

