/**
 * Juno
 * Juno Public API Docs
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';
import { CustomGraphType } from './customGraphType';

export class CustomGraphTypeResponse {
    /**
    * Graph types
    */
    'graphs': Array<CustomGraphType>;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "graphs",
            "baseName": "graphs",
            "type": "Array<CustomGraphType>"
        }    ];

    static getAttributeTypeMap() {
        return CustomGraphTypeResponse.attributeTypeMap;
    }
}

