/**
 * Juno
 * Juno Public API Docs
 *
 * The version of the OpenAPI document: 1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';

export class CustomGraphType {
  /**
   * Graph ID
   */
  'id': string;
  /**
   * Event type ID
   */
  'eventTypeId': string;
  /**
   * Project ID
   */
  'projectId': string;
  /**
   * Graph title
   */
  'graphTitle': string;
  /**
   * X-axis property
   */
  'xProperty': string;
  /**
   * Y-axis property
   */
  'yProperty': string;
  /**
   * Graph type
   */
  'graphType': string;
  /**
   * Caption
   */
  'caption': string;

  static discriminator: string | undefined = undefined;

  static attributeTypeMap: Array<{
    name: string;
    baseName: string;
    type: string;
  }> = [
    {
      name: 'id',
      baseName: 'id',
      type: 'string',
    },
    {
      name: 'eventTypeId',
      baseName: 'eventTypeId',
      type: 'string',
    },
    {
      name: 'projectId',
      baseName: 'projectId',
      type: 'string',
    },
    {
      name: 'graphTitle',
      baseName: 'graphTitle',
      type: 'string',
    },
    {
      name: 'xProperty',
      baseName: 'xProperty',
      type: 'string',
    },
    {
      name: 'yProperty',
      baseName: 'yProperty',
      type: 'string',
    },
    {
      name: 'graphType',
      baseName: 'graphType',
      type: 'string',
    },
    {
      name: 'caption',
      baseName: 'caption',
      type: 'string',
    },
  ];

  static getAttributeTypeMap() {
    return CustomGraphType.attributeTypeMap;
  }
}
