/**
 * Juno
 * Juno Public API Docs
 *
 * The version of the OpenAPI document: 1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';

export class DeleteFileBucketModel {
  /**
   * The unique name of the bucket
   */
  'name': string;
  /**
   * Configuration ID for the bucket
   */
  'configId': number;
  /**
   * The file provider name associated with the bucket
   */
  'fileProviderName': string;

  static discriminator: string | undefined = undefined;

  static attributeTypeMap: Array<{
    name: string;
    baseName: string;
    type: string;
  }> = [
    {
      name: 'name',
      baseName: 'name',
      type: 'string',
    },
    {
      name: 'configId',
      baseName: 'configId',
      type: 'number',
    },
    {
      name: 'fileProviderName',
      baseName: 'fileProviderName',
      type: 'string',
    },
  ];

  static getAttributeTypeMap() {
    return DeleteFileBucketModel.attributeTypeMap;
  }
}
