/**
 * Juno
 * Juno Public API Docs
 *
 * The version of the OpenAPI document: 1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

export class DownloadFileModel {
  /**
   * The name of the bucket to use for downloading
   */
  'bucketName': string;
  /**
   * The config id of the file to use for downloading
   */
  'configId': number;
  /**
   * The name of the file to use for downloading
   */
  'fileName': string;
  /**
   * The name of the provider to connect to for downloading
   */
  'providerName': string;
  /**
   * The region to use for downloading
   */
  'region'?: string;

  static discriminator: string | undefined = undefined;

  static attributeTypeMap: Array<{
    name: string;
    baseName: string;
    type: string;
  }> = [
    {
      name: 'bucketName',
      baseName: 'bucketName',
      type: 'string',
    },
    {
      name: 'configId',
      baseName: 'configId',
      type: 'number',
    },
    {
      name: 'fileName',
      baseName: 'fileName',
      type: 'string',
    },
    {
      name: 'providerName',
      baseName: 'providerName',
      type: 'string',
    },
    {
      name: 'region',
      baseName: 'region',
      type: 'string',
    },
  ];

  static getAttributeTypeMap() {
    return DownloadFileModel.attributeTypeMap;
  }
}
