/**
 * Juno
 * Juno Public API Docs
 *
 * The version of the OpenAPI document: 1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { EmailDomain } from './emailDomain';
import { EmailSender } from './emailSender';

export class EmailConfigResponse {
  /**
   * Email Configuration ID
   */
  'id': number;
  /**
   * The configured environment
   */
  'environment': string;
  /**
   * The configured sendGrid key
   */
  'sendgridKey': string;
  /**
   * The list of domains associated with the email config
   */
  'domains': Array<EmailDomain>;
  /**
   * The list of senders associated with the email config
   */
  'senders': Array<EmailSender>;

  static discriminator: string | undefined = undefined;

  static attributeTypeMap: Array<{
    name: string;
    baseName: string;
    type: string;
  }> = [
    {
      name: 'id',
      baseName: 'id',
      type: 'number',
    },
    {
      name: 'environment',
      baseName: 'environment',
      type: 'string',
    },
    {
      name: 'sendgridKey',
      baseName: 'sendgridKey',
      type: 'string',
    },
    {
      name: 'domains',
      baseName: 'domains',
      type: 'Array<EmailDomain>',
    },
    {
      name: 'senders',
      baseName: 'senders',
      type: 'Array<EmailSender>',
    },
  ];

  static getAttributeTypeMap() {
    return EmailConfigResponse.attributeTypeMap;
  }
}
