/**
 * Juno
 * Juno Public API Docs
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';
import { FileBucket } from './fileBucket';

export class FileConfigResponse {
    /**
    * File Configuration ID
    */
    'id': number;
    /**
    * The configured environment
    */
    'environment': string;
    /**
    * The list of files associated with the config
    */
    'files': Array<any>;
    /**
    * The list of buckets associated with the config
    */
    'buckets': Array<FileBucket>;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "id",
            "baseName": "id",
            "type": "number"
        },
        {
            "name": "environment",
            "baseName": "environment",
            "type": "string"
        },
        {
            "name": "files",
            "baseName": "files",
            "type": "Array<any>"
        },
        {
            "name": "buckets",
            "baseName": "buckets",
            "type": "Array<FileBucket>"
        }    ];

    static getAttributeTypeMap() {
        return FileConfigResponse.attributeTypeMap;
    }
}

