/**
 * Juno
 * Juno Public API Docs
 *
 * The version of the OpenAPI document: 1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { InputEventResponse } from './inputEventResponse';

export class GetAllInputEventsResponse {
  /**
   * All input events
   */
  'events': Array<InputEventResponse>;

  static discriminator: string | undefined = undefined;

  static attributeTypeMap: Array<{
    name: string;
    baseName: string;
    type: string;
  }> = [
    {
      name: 'events',
      baseName: 'events',
      type: 'Array<InputEventResponse>',
    },
  ];

  static getAttributeTypeMap() {
    return GetAllInputEventsResponse.attributeTypeMap;
  }
}
