/**
 * Juno
 * Juno Public API Docs
 *
 * The version of the OpenAPI document: 1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';
import { CustomEventResponse } from './customEventResponse';

export class GetAllCustomEventsResponse {
  /**
   * All custom events
   */
  'events': Array<CustomEventResponse>;

  static discriminator: string | undefined = undefined;

  static attributeTypeMap: Array<{
    name: string;
    baseName: string;
    type: string;
  }> = [
    {
      name: 'events',
      baseName: 'events',
      type: 'Array<CustomEventResponse>',
    },
  ];

  static getAttributeTypeMap() {
    return GetAllCustomEventsResponse.attributeTypeMap;
  }
}
