/**
 * Juno
 * Juno Public API Docs
 *
 * The version of the OpenAPI document: 1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';
import { ClickEventResponse } from './clickEventResponse';

export class GetAllClickEventsResponse {
  /**
   * All click events
   */
  'events': Array<ClickEventResponse>;

  static discriminator: string | undefined = undefined;

  static attributeTypeMap: Array<{
    name: string;
    baseName: string;
    type: string;
  }> = [
    {
      name: 'events',
      baseName: 'events',
      type: 'Array<ClickEventResponse>',
    },
  ];

  static getAttributeTypeMap() {
    return GetAllClickEventsResponse.attributeTypeMap;
  }
}
