/**
 * Juno
 * Juno Public API Docs
 *
 * The version of the OpenAPI document: 1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { VisitEventResponse } from './visitEventResponse';

export class GetAllVisitEventsResponse {
  /**
   * All visit events
   */
  'events': Array<VisitEventResponse>;

  static discriminator: string | undefined = undefined;

  static attributeTypeMap: Array<{
    name: string;
    baseName: string;
    type: string;
  }> = [
    {
      name: 'events',
      baseName: 'events',
      type: 'Array<VisitEventResponse>',
    },
  ];

  static getAttributeTypeMap() {
    return GetAllVisitEventsResponse.attributeTypeMap;
  }
}
