/**
 * Juno
 * Juno Public API Docs
 *
 * The version of the OpenAPI document: 1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';
import { CustomEventResponse } from './customEventResponse';

export class GetCustomEventsResponse {
  /**
   * Custom events
   */
  'events': Array<CustomEventResponse>;
  /**
   * Pagination cursor
   */
  'afterId': string;

  static discriminator: string | undefined = undefined;

  static attributeTypeMap: Array<{
    name: string;
    baseName: string;
    type: string;
  }> = [
    {
      name: 'events',
      baseName: 'events',
      type: 'Array<CustomEventResponse>',
    },
    {
      name: 'afterId',
      baseName: 'afterId',
      type: 'string',
    },
  ];

  static getAttributeTypeMap() {
    return GetCustomEventsResponse.attributeTypeMap;
  }
}
