/**
 * Juno
 * Juno Public API Docs
 *
 * The version of the OpenAPI document: 1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

export class IssueApiKeyResponse {
  /**
   * The generated API key
   */
  'apiKey': string;

  static discriminator: string | undefined = undefined;

  static attributeTypeMap: Array<{
    name: string;
    baseName: string;
    type: string;
  }> = [
    {
      name: 'apiKey',
      baseName: 'apiKey',
      type: 'string',
    },
  ];

  static getAttributeTypeMap() {
    return IssueApiKeyResponse.attributeTypeMap;
  }
}
