/**
 * Juno
 * Juno Public API Docs
 *
 * The version of the OpenAPI document: 1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';

export class LinkUserModel {
  /**
   * The ID of the user
   */
  'id'?: number;
  /**
   * The email of the user
   */
  'email'?: string;

  static discriminator: string | undefined = undefined;

  static attributeTypeMap: Array<{
    name: string;
    baseName: string;
    type: string;
  }> = [
    {
      name: 'id',
      baseName: 'id',
      type: 'number',
    },
    {
      name: 'email',
      baseName: 'email',
      type: 'string',
    },
  ];

  static getAttributeTypeMap() {
    return LinkUserModel.attributeTypeMap;
  }
}
