/**
 * Juno
 * Juno Public API Docs
 *
 * The version of the OpenAPI document: 1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';

export class LogClickEventRequest {
  /**
   * The ID of the object that was clicked
   */
  'objectId': string;
  /**
   * The ID of the user who performed the click
   */
  'userId': string;

  static discriminator: string | undefined = undefined;

  static attributeTypeMap: Array<{
    name: string;
    baseName: string;
    type: string;
  }> = [
    {
      name: 'objectId',
      baseName: 'objectId',
      type: 'string',
    },
    {
      name: 'userId',
      baseName: 'userId',
      type: 'string',
    },
  ];

  static getAttributeTypeMap() {
    return LogClickEventRequest.attributeTypeMap;
  }
}
