/**
 * Juno
 * Juno Public API Docs
 *
 * The version of the OpenAPI document: 1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

export class LogCustomEventRequest {
  /**
   * The category of the custom event
   */
  'category': string;
  /**
   * The subcategory of the custom event
   */
  'subcategory': string;
  /**
   * Custom properties for the event
   */
  'properties': object;

  static discriminator: string | undefined = undefined;

  static attributeTypeMap: Array<{
    name: string;
    baseName: string;
    type: string;
  }> = [
    {
      name: 'category',
      baseName: 'category',
      type: 'string',
    },
    {
      name: 'subcategory',
      baseName: 'subcategory',
      type: 'string',
    },
    {
      name: 'properties',
      baseName: 'properties',
      type: 'object',
    },
  ];

  static getAttributeTypeMap() {
    return LogCustomEventRequest.attributeTypeMap;
  }
}
