/**
 * Juno
 * Juno Public API Docs
 *
 * The version of the OpenAPI document: 1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';

export class LogInputEventRequest {
  /**
   * The ID of the input object
   */
  'objectId': string;
  /**
   * The ID of the user who interacted with the input
   */
  'userId': string;
  /**
   * The text value entered in the input
   */
  'textValue': string;

  static discriminator: string | undefined = undefined;

  static attributeTypeMap: Array<{
    name: string;
    baseName: string;
    type: string;
  }> = [
    {
      name: 'objectId',
      baseName: 'objectId',
      type: 'string',
    },
    {
      name: 'userId',
      baseName: 'userId',
      type: 'string',
    },
    {
      name: 'textValue',
      baseName: 'textValue',
      type: 'string',
    },
  ];

  static getAttributeTypeMap() {
    return LogInputEventRequest.attributeTypeMap;
  }
}
