/**
 * Juno
 * Juno Public API Docs
 *
 * The version of the OpenAPI document: 1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';
import { NewAccountRequestResponse } from './newAccountRequestResponse';

export class NewAccountRequestsResponse {
  /**
   * List of new account requests
   */
  'requests': Array<NewAccountRequestResponse>;

  static discriminator: string | undefined = undefined;

  static attributeTypeMap: Array<{
    name: string;
    baseName: string;
    type: string;
  }> = [
    {
      name: 'requests',
      baseName: 'requests',
      type: 'Array<NewAccountRequestResponse>',
    },
  ];

  static getAttributeTypeMap() {
    return NewAccountRequestsResponse.attributeTypeMap;
  }
}
