/**
 * Juno
 * Juno Public API Docs
 *
 * The version of the OpenAPI document: 1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';
import { AccessKey } from './accessKey';

export class RegisterFileProviderModel {
  /**
   * The access key to register with
   */
  'accessKey': Array<AccessKey>;
  /**
   * The base url associated with file provider.
   */
  'baseUrl': string;
  /**
   * The file provider name being registered.
   */
  'providerName': string;

  static discriminator: string | undefined = undefined;

  static attributeTypeMap: Array<{
    name: string;
    baseName: string;
    type: string;
  }> = [
    {
      name: 'accessKey',
      baseName: 'accessKey',
      type: 'Array<AccessKey>',
    },
    {
      name: 'baseUrl',
      baseName: 'baseUrl',
      type: 'string',
    },
    {
      name: 'providerName',
      baseName: 'providerName',
      type: 'string',
    },
  ];

  static getAttributeTypeMap() {
    return RegisterFileProviderModel.attributeTypeMap;
  }
}
