/**
 * Juno
 * Juno Public API Docs
 *
 * The version of the OpenAPI document: 1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';
import { SendGridDNSResponse } from './sendGridDNSResponse';

export class RegisterDomainResponse {
  'id': number;
  'valid': string;
  'records': SendGridDNSResponse;
  'statusCode': number;

  static discriminator: string | undefined = undefined;

  static attributeTypeMap: Array<{
    name: string;
    baseName: string;
    type: string;
  }> = [
    {
      name: 'id',
      baseName: 'id',
      type: 'number',
    },
    {
      name: 'valid',
      baseName: 'valid',
      type: 'string',
    },
    {
      name: 'records',
      baseName: 'records',
      type: 'SendGridDNSResponse',
    },
    {
      name: 'statusCode',
      baseName: 'statusCode',
      type: 'number',
    },
  ];

  static getAttributeTypeMap() {
    return RegisterDomainResponse.attributeTypeMap;
  }
}
