/**
 * Juno
 * Juno Public API Docs
 *
 * The version of the OpenAPI document: 1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';

export class RequestNewAccountModel {
  /**
   * Email for the new account
   */
  'email': string;
  /**
   * Name of the requester
   */
  'name': string;
  /**
   * Password for the new account
   */
  'password': string;
  /**
   * Requested user type / role
   */
  'userType': RequestNewAccountModel.UserTypeEnum;
  /**
   * Optional project name to associate
   */
  'projectName'?: string;

  static discriminator: string | undefined = undefined;

  static attributeTypeMap: Array<{
    name: string;
    baseName: string;
    type: string;
  }> = [
    {
      name: 'email',
      baseName: 'email',
      type: 'string',
    },
    {
      name: 'name',
      baseName: 'name',
      type: 'string',
    },
    {
      name: 'password',
      baseName: 'password',
      type: 'string',
    },
    {
      name: 'userType',
      baseName: 'userType',
      type: 'RequestNewAccountModel.UserTypeEnum',
    },
    {
      name: 'projectName',
      baseName: 'projectName',
      type: 'string',
    },
  ];

  static getAttributeTypeMap() {
    return RequestNewAccountModel.attributeTypeMap;
  }
}

export namespace RequestNewAccountModel {
  export enum UserTypeEnum {
    Superadmin = <any>'SUPERADMIN',
    Admin = <any>'ADMIN',
    User = <any>'USER',
  }
}
