/**
 * Juno
 * Juno Public API Docs
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';

export class SendEmailStatisticsResponse {
    /**
    * Date
    */
    'date': string;
    /**
    * The number of links that were clicked in your emails.
    */
    'clicks': number;
    /**
    * The number of unique recipients who clicked links in your emails.
    */
    'uniqueClicks': number;
    /**
    * The total number of times your emails were opened by recipients.
    */
    'opens': number;
    /**
    * The number of unique recipients who opened your emails.
    */
    'uniqueOpens': number;
    /**
    * The number of emails that were not allowed to be delivered by ISPs.
    */
    'blocks': number;
    /**
    * The number of emails that were dropped because of a bounce.
    */
    'bounceDrops': number;
    /**
    * The number of emails that bounced instead of being delivered.
    */
    'bounces': number;
    /**
    * The number of emails that temporarily could not be delivered.
    */
    'deferred': number;
    /**
    * The number of emails confirmed to have been delivered.
    */
    'delivered': number;
    /**
    * The number of recipients with malformed or invalid email addresses.
    */
    'invalidEmails': number;
    /**
    * Requests from your website, application, or mail client via SMTP Relay or API.
    */
    'processed': number;
    /**
    * The number of emails that were requested to be delivered.
    */
    'requests': number;
    /**
    * The number of emails dropped due to a recipient marking your email as spam.
    */
    'spamReportDrops': number;
    /**
    * The number of recipients who marked your email as spam.
    */
    'spamReports': number;
    /**
    * The number of emails dropped due to a recipient unsubscribing.
    */
    'unsubscribeDrops': number;
    /**
    * The number of recipients who unsubscribed from your emails.
    */
    'unsubscribes': number;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "date",
            "baseName": "date",
            "type": "string"
        },
        {
            "name": "clicks",
            "baseName": "clicks",
            "type": "number"
        },
        {
            "name": "uniqueClicks",
            "baseName": "unique_clicks",
            "type": "number"
        },
        {
            "name": "opens",
            "baseName": "opens",
            "type": "number"
        },
        {
            "name": "uniqueOpens",
            "baseName": "unique_opens",
            "type": "number"
        },
        {
            "name": "blocks",
            "baseName": "blocks",
            "type": "number"
        },
        {
            "name": "bounceDrops",
            "baseName": "bounce_drops",
            "type": "number"
        },
        {
            "name": "bounces",
            "baseName": "bounces",
            "type": "number"
        },
        {
            "name": "deferred",
            "baseName": "deferred",
            "type": "number"
        },
        {
            "name": "delivered",
            "baseName": "delivered",
            "type": "number"
        },
        {
            "name": "invalidEmails",
            "baseName": "invalid_emails",
            "type": "number"
        },
        {
            "name": "processed",
            "baseName": "processed",
            "type": "number"
        },
        {
            "name": "requests",
            "baseName": "requests",
            "type": "number"
        },
        {
            "name": "spamReportDrops",
            "baseName": "spam_report_drops",
            "type": "number"
        },
        {
            "name": "spamReports",
            "baseName": "spam_reports",
            "type": "number"
        },
        {
            "name": "unsubscribeDrops",
            "baseName": "unsubscribe_drops",
            "type": "number"
        },
        {
            "name": "unsubscribes",
            "baseName": "unsubscribes",
            "type": "number"
        }    ];

    static getAttributeTypeMap() {
        return SendEmailStatisticsResponse.attributeTypeMap;
    }
}

