/**
 * Juno
 * Juno Public API Docs
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';
import { SendEmailStatisticsResponse } from './sendEmailStatisticsResponse';

export class SendEmailStatisticsResponses {
    /**
    * List of email analytics.
    */
    'responses': Array<SendEmailStatisticsResponse>;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "responses",
            "baseName": "responses",
            "type": "Array<SendEmailStatisticsResponse>"
        }    ];

    static getAttributeTypeMap() {
        return SendEmailStatisticsResponses.attributeTypeMap;
    }
}

