/**
 * Juno
 * Juno Public API Docs
 *
 * The version of the OpenAPI document: 1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';
import { VisitEventProperties } from './visitEventProperties';

export class VisitEventResponse {
  /**
   * Event ID
   */
  'id': string;
  /**
   * Event category
   */
  'category': string;
  /**
   * Event subcategory
   */
  'subcategory': string;
  /**
   * Project ID
   */
  'projectId': string;
  /**
   * Environment
   */
  'environment': string;
  /**
   * Created timestamp
   */
  'createdAt': string;
  /**
   * Updated timestamp
   */
  'updatedAt': string;
  /**
   * Event properties
   */
  'eventProperties': VisitEventProperties;

  static discriminator: string | undefined = undefined;

  static attributeTypeMap: Array<{
    name: string;
    baseName: string;
    type: string;
  }> = [
    {
      name: 'id',
      baseName: 'id',
      type: 'string',
    },
    {
      name: 'category',
      baseName: 'category',
      type: 'string',
    },
    {
      name: 'subcategory',
      baseName: 'subcategory',
      type: 'string',
    },
    {
      name: 'projectId',
      baseName: 'projectId',
      type: 'string',
    },
    {
      name: 'environment',
      baseName: 'environment',
      type: 'string',
    },
    {
      name: 'createdAt',
      baseName: 'createdAt',
      type: 'string',
    },
    {
      name: 'updatedAt',
      baseName: 'updatedAt',
      type: 'string',
    },
    {
      name: 'eventProperties',
      baseName: 'eventProperties',
      type: 'VisitEventProperties',
    },
  ];

  static getAttributeTypeMap() {
    return VisitEventResponse.attributeTypeMap;
  }
}
