/* tslint:disable */
/* eslint-disable */
/**
 * Juno
 * Juno Public API Docs
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface AccessKey
 */
export interface AccessKey {
    /**
     * Client public access key
     * @type {string}
     * @memberof AccessKey
     */
    publicAccessKey: string;
    /**
     * Client private access key
     * @type {string}
     * @memberof AccessKey
     */
    privateAccessKey: string;
}

/**
 * Check if a given object implements the AccessKey interface.
 */
export function instanceOfAccessKey(value: object): value is AccessKey {
    if (!('publicAccessKey' in value) || value['publicAccessKey'] === undefined) return false;
    if (!('privateAccessKey' in value) || value['privateAccessKey'] === undefined) return false;
    return true;
}

export function AccessKeyFromJSON(json: any): AccessKey {
    return AccessKeyFromJSONTyped(json, false);
}

export function AccessKeyFromJSONTyped(json: any, ignoreDiscriminator: boolean): AccessKey {
    if (json == null) {
        return json;
    }
    return {
        
        'publicAccessKey': json['publicAccessKey'],
        'privateAccessKey': json['privateAccessKey'],
    };
}

export function AccessKeyToJSON(value?: AccessKey | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'publicAccessKey': value['publicAccessKey'],
        'privateAccessKey': value['privateAccessKey'],
    };
}

