/* tslint:disable */
/* eslint-disable */
/**
 * Juno
 * Juno Public API Docs
 *
 * The version of the OpenAPI document: 1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { AcceptAccountRequestResponseProject } from './AcceptAccountRequestResponseProject';
import {
  AcceptAccountRequestResponseProjectFromJSON,
  AcceptAccountRequestResponseProjectFromJSONTyped,
  AcceptAccountRequestResponseProjectToJSON,
} from './AcceptAccountRequestResponseProject';
import type { AcceptAccountRequestResponseUser } from './AcceptAccountRequestResponseUser';
import {
  AcceptAccountRequestResponseUserFromJSON,
  AcceptAccountRequestResponseUserFromJSONTyped,
  AcceptAccountRequestResponseUserToJSON,
} from './AcceptAccountRequestResponseUser';

/**
 *
 * @export
 * @interface AcceptAccountRequestResponseModel
 */
export interface AcceptAccountRequestResponseModel {
  /**
   * The created user
   * @type {AcceptAccountRequestResponseUser}
   * @memberof AcceptAccountRequestResponseModel
   */
  user: AcceptAccountRequestResponseUser;
  /**
   * The created or linked project (if applicable)
   * @type {AcceptAccountRequestResponseProject}
   * @memberof AcceptAccountRequestResponseModel
   */
  project?: AcceptAccountRequestResponseProject;
}

/**
 * Check if a given object implements the AcceptAccountRequestResponseModel interface.
 */
export function instanceOfAcceptAccountRequestResponseModel(
  value: object
): value is AcceptAccountRequestResponseModel {
  if (!('user' in value) || value['user'] === undefined) return false;
  return true;
}

export function AcceptAccountRequestResponseModelFromJSON(
  json: any
): AcceptAccountRequestResponseModel {
  return AcceptAccountRequestResponseModelFromJSONTyped(json, false);
}

export function AcceptAccountRequestResponseModelFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean
): AcceptAccountRequestResponseModel {
  if (json == null) {
    return json;
  }
  return {
    user: AcceptAccountRequestResponseUserFromJSON(json['user']),
    project:
      json['project'] == null
        ? undefined
        : AcceptAccountRequestResponseProjectFromJSON(json['project']),
  };
}

export function AcceptAccountRequestResponseModelToJSON(
  value?: AcceptAccountRequestResponseModel | null
): any {
  if (value == null) {
    return value;
  }
  return {
    user: AcceptAccountRequestResponseUserToJSON(value['user']),
    project: AcceptAccountRequestResponseProjectToJSON(value['project']),
  };
}
