/* tslint:disable */
/* eslint-disable */
/**
 * Juno
 * Juno Public API Docs
 *
 * The version of the OpenAPI document: 1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 *
 * @export
 * @interface AcceptAccountRequestResponseProject
 */
export interface AcceptAccountRequestResponseProject {
  /**
   * Project ID
   * @type {number}
   * @memberof AcceptAccountRequestResponseProject
   */
  id: number;
  /**
   * Project name
   * @type {string}
   * @memberof AcceptAccountRequestResponseProject
   */
  name: string;
}

/**
 * Check if a given object implements the AcceptAccountRequestResponseProject interface.
 */
export function instanceOfAcceptAccountRequestResponseProject(
  value: object
): value is AcceptAccountRequestResponseProject {
  if (!('id' in value) || value['id'] === undefined) return false;
  if (!('name' in value) || value['name'] === undefined) return false;
  return true;
}

export function AcceptAccountRequestResponseProjectFromJSON(
  json: any
): AcceptAccountRequestResponseProject {
  return AcceptAccountRequestResponseProjectFromJSONTyped(json, false);
}

export function AcceptAccountRequestResponseProjectFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean
): AcceptAccountRequestResponseProject {
  if (json == null) {
    return json;
  }
  return {
    id: json['id'],
    name: json['name'],
  };
}

export function AcceptAccountRequestResponseProjectToJSON(
  value?: AcceptAccountRequestResponseProject | null
): any {
  if (value == null) {
    return value;
  }
  return {
    id: value['id'],
    name: value['name'],
  };
}
