/* tslint:disable */
/* eslint-disable */
/**
 * Juno
 * Juno Public API Docs
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * 
 * @export
 */
export const AggregateInterval = {
    Day: 'day',
    Week: 'week',
    Month: 'month'
} as const;
export type AggregateInterval = typeof AggregateInterval[keyof typeof AggregateInterval];


export function instanceOfAggregateInterval(value: any): boolean {
    for (const key in AggregateInterval) {
        if (Object.prototype.hasOwnProperty.call(AggregateInterval, key)) {
            if (AggregateInterval[key as keyof typeof AggregateInterval] === value) {
                return true;
            }
        }
    }
    return false;
}

export function AggregateIntervalFromJSON(json: any): AggregateInterval {
    return AggregateIntervalFromJSONTyped(json, false);
}

export function AggregateIntervalFromJSONTyped(json: any, ignoreDiscriminator: boolean): AggregateInterval {
    return json as AggregateInterval;
}

export function AggregateIntervalToJSON(value?: AggregateInterval | null): any {
    return value as any;
}

