/* tslint:disable */
/* eslint-disable */
/**
 * Juno
 * Juno Public API Docs
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface AnalyticsConfigResponse
 */
export interface AnalyticsConfigResponse {
    /**
     * 
     * @type {number}
     * @memberof AnalyticsConfigResponse
     */
    id: number;
    /**
     * 
     * @type {string}
     * @memberof AnalyticsConfigResponse
     */
    environment: string;
    /**
     * 
     * @type {string}
     * @memberof AnalyticsConfigResponse
     */
    serverAnalyticsKey: string;
    /**
     * 
     * @type {string}
     * @memberof AnalyticsConfigResponse
     */
    clientAnalyticsKey: string;
}

/**
 * Check if a given object implements the AnalyticsConfigResponse interface.
 */
export function instanceOfAnalyticsConfigResponse(value: object): value is AnalyticsConfigResponse {
    if (!('id' in value) || value['id'] === undefined) return false;
    if (!('environment' in value) || value['environment'] === undefined) return false;
    if (!('serverAnalyticsKey' in value) || value['serverAnalyticsKey'] === undefined) return false;
    if (!('clientAnalyticsKey' in value) || value['clientAnalyticsKey'] === undefined) return false;
    return true;
}

export function AnalyticsConfigResponseFromJSON(json: any): AnalyticsConfigResponse {
    return AnalyticsConfigResponseFromJSONTyped(json, false);
}

export function AnalyticsConfigResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): AnalyticsConfigResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'],
        'environment': json['environment'],
        'serverAnalyticsKey': json['serverAnalyticsKey'],
        'clientAnalyticsKey': json['clientAnalyticsKey'],
    };
}

export function AnalyticsConfigResponseToJSON(value?: AnalyticsConfigResponse | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'id': value['id'],
        'environment': value['environment'],
        'serverAnalyticsKey': value['serverAnalyticsKey'],
        'clientAnalyticsKey': value['clientAnalyticsKey'],
    };
}

