/* tslint:disable */
/* eslint-disable */
/**
 * Juno
 * Juno Public API Docs
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { ClickEventProperties } from './ClickEventProperties';
import {
    ClickEventPropertiesFromJSON,
    ClickEventPropertiesFromJSONTyped,
    ClickEventPropertiesToJSON,
} from './ClickEventProperties';

/**
 * 
 * @export
 * @interface ClickEventResponse
 */
export interface ClickEventResponse {
    /**
     * Event ID
     * @type {string}
     * @memberof ClickEventResponse
     */
    id: string;
    /**
     * Event category
     * @type {string}
     * @memberof ClickEventResponse
     */
    category: string;
    /**
     * Event subcategory
     * @type {string}
     * @memberof ClickEventResponse
     */
    subcategory: string;
    /**
     * Project ID
     * @type {string}
     * @memberof ClickEventResponse
     */
    projectId: string;
    /**
     * Environment
     * @type {string}
     * @memberof ClickEventResponse
     */
    environment: string;
    /**
     * Created timestamp
     * @type {string}
     * @memberof ClickEventResponse
     */
    createdAt: string;
    /**
     * Updated timestamp
     * @type {string}
     * @memberof ClickEventResponse
     */
    updatedAt: string;
    /**
     * Event properties
     * @type {ClickEventProperties}
     * @memberof ClickEventResponse
     */
    eventProperties: ClickEventProperties;
}

/**
 * Check if a given object implements the ClickEventResponse interface.
 */
export function instanceOfClickEventResponse(value: object): value is ClickEventResponse {
    if (!('id' in value) || value['id'] === undefined) return false;
    if (!('category' in value) || value['category'] === undefined) return false;
    if (!('subcategory' in value) || value['subcategory'] === undefined) return false;
    if (!('projectId' in value) || value['projectId'] === undefined) return false;
    if (!('environment' in value) || value['environment'] === undefined) return false;
    if (!('createdAt' in value) || value['createdAt'] === undefined) return false;
    if (!('updatedAt' in value) || value['updatedAt'] === undefined) return false;
    if (!('eventProperties' in value) || value['eventProperties'] === undefined) return false;
    return true;
}

export function ClickEventResponseFromJSON(json: any): ClickEventResponse {
    return ClickEventResponseFromJSONTyped(json, false);
}

export function ClickEventResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): ClickEventResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'],
        'category': json['category'],
        'subcategory': json['subcategory'],
        'projectId': json['projectId'],
        'environment': json['environment'],
        'createdAt': json['createdAt'],
        'updatedAt': json['updatedAt'],
        'eventProperties': ClickEventPropertiesFromJSON(json['eventProperties']),
    };
}

export function ClickEventResponseToJSON(value?: ClickEventResponse | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'id': value['id'],
        'category': value['category'],
        'subcategory': value['subcategory'],
        'projectId': value['projectId'],
        'environment': value['environment'],
        'createdAt': value['createdAt'],
        'updatedAt': value['updatedAt'],
        'eventProperties': ClickEventPropertiesToJSON(value['eventProperties']),
    };
}

