/* tslint:disable */
/* eslint-disable */
/**
 * Juno
 * Juno Public API Docs
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface CreateAnalyticsConfigModel
 */
export interface CreateAnalyticsConfigModel {
    /**
     * 
     * @type {string}
     * @memberof CreateAnalyticsConfigModel
     */
    serverAnalyticsKey: string;
    /**
     * 
     * @type {string}
     * @memberof CreateAnalyticsConfigModel
     */
    clientAnalyticsKey: string;
}

/**
 * Check if a given object implements the CreateAnalyticsConfigModel interface.
 */
export function instanceOfCreateAnalyticsConfigModel(value: object): value is CreateAnalyticsConfigModel {
    if (!('serverAnalyticsKey' in value) || value['serverAnalyticsKey'] === undefined) return false;
    if (!('clientAnalyticsKey' in value) || value['clientAnalyticsKey'] === undefined) return false;
    return true;
}

export function CreateAnalyticsConfigModelFromJSON(json: any): CreateAnalyticsConfigModel {
    return CreateAnalyticsConfigModelFromJSONTyped(json, false);
}

export function CreateAnalyticsConfigModelFromJSONTyped(json: any, ignoreDiscriminator: boolean): CreateAnalyticsConfigModel {
    if (json == null) {
        return json;
    }
    return {
        
        'serverAnalyticsKey': json['serverAnalyticsKey'],
        'clientAnalyticsKey': json['clientAnalyticsKey'],
    };
}

export function CreateAnalyticsConfigModelToJSON(value?: CreateAnalyticsConfigModel | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'serverAnalyticsKey': value['serverAnalyticsKey'],
        'clientAnalyticsKey': value['clientAnalyticsKey'],
    };
}

