/* tslint:disable */
/* eslint-disable */
/**
 * Juno
 * Juno Public API Docs
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface CreateUserModel
 */
export interface CreateUserModel {
    /**
     * User email
     * @type {string}
     * @memberof CreateUserModel
     */
    email: string;
    /**
     * User name
     * @type {string}
     * @memberof CreateUserModel
     */
    name: string;
    /**
     * User password
     * @type {string}
     * @memberof CreateUserModel
     */
    password: string;
}

/**
 * Check if a given object implements the CreateUserModel interface.
 */
export function instanceOfCreateUserModel(value: object): value is CreateUserModel {
    if (!('email' in value) || value['email'] === undefined) return false;
    if (!('name' in value) || value['name'] === undefined) return false;
    if (!('password' in value) || value['password'] === undefined) return false;
    return true;
}

export function CreateUserModelFromJSON(json: any): CreateUserModel {
    return CreateUserModelFromJSONTyped(json, false);
}

export function CreateUserModelFromJSONTyped(json: any, ignoreDiscriminator: boolean): CreateUserModel {
    if (json == null) {
        return json;
    }
    return {
        
        'email': json['email'],
        'name': json['name'],
        'password': json['password'],
    };
}

export function CreateUserModelToJSON(value?: CreateUserModel | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'email': value['email'],
        'name': value['name'],
        'password': value['password'],
    };
}

