/* tslint:disable */
/* eslint-disable */
/**
 * Juno
 * Juno Public API Docs
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface CreateProjectModel
 */
export interface CreateProjectModel {
    /**
     * The name of the project
     * @type {string}
     * @memberof CreateProjectModel
     */
    name: string;
}

/**
 * Check if a given object implements the CreateProjectModel interface.
 */
export function instanceOfCreateProjectModel(value: object): value is CreateProjectModel {
    if (!('name' in value) || value['name'] === undefined) return false;
    return true;
}

export function CreateProjectModelFromJSON(json: any): CreateProjectModel {
    return CreateProjectModelFromJSONTyped(json, false);
}

export function CreateProjectModelFromJSONTyped(json: any, ignoreDiscriminator: boolean): CreateProjectModel {
    if (json == null) {
        return json;
    }
    return {
        
        'name': json['name'],
    };
}

export function CreateProjectModelToJSON(value?: CreateProjectModel | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'name': value['name'],
    };
}

