/* tslint:disable */
/* eslint-disable */
/**
 * Juno
 * Juno Public API Docs
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface CustomGraphType
 */
export interface CustomGraphType {
    /**
     * Graph ID
     * @type {string}
     * @memberof CustomGraphType
     */
    id: string;
    /**
     * Event type ID
     * @type {string}
     * @memberof CustomGraphType
     */
    eventTypeId: string;
    /**
     * Project ID
     * @type {string}
     * @memberof CustomGraphType
     */
    projectId: string;
    /**
     * Graph title
     * @type {string}
     * @memberof CustomGraphType
     */
    graphTitle: string;
    /**
     * X-axis property
     * @type {string}
     * @memberof CustomGraphType
     */
    xProperty: string;
    /**
     * Y-axis property
     * @type {string}
     * @memberof CustomGraphType
     */
    yProperty: string;
    /**
     * Graph type
     * @type {string}
     * @memberof CustomGraphType
     */
    graphType: string;
    /**
     * Caption
     * @type {string}
     * @memberof CustomGraphType
     */
    caption: string;
}

/**
 * Check if a given object implements the CustomGraphType interface.
 */
export function instanceOfCustomGraphType(value: object): value is CustomGraphType {
    if (!('id' in value) || value['id'] === undefined) return false;
    if (!('eventTypeId' in value) || value['eventTypeId'] === undefined) return false;
    if (!('projectId' in value) || value['projectId'] === undefined) return false;
    if (!('graphTitle' in value) || value['graphTitle'] === undefined) return false;
    if (!('xProperty' in value) || value['xProperty'] === undefined) return false;
    if (!('yProperty' in value) || value['yProperty'] === undefined) return false;
    if (!('graphType' in value) || value['graphType'] === undefined) return false;
    if (!('caption' in value) || value['caption'] === undefined) return false;
    return true;
}

export function CustomGraphTypeFromJSON(json: any): CustomGraphType {
    return CustomGraphTypeFromJSONTyped(json, false);
}

export function CustomGraphTypeFromJSONTyped(json: any, ignoreDiscriminator: boolean): CustomGraphType {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'],
        'eventTypeId': json['eventTypeId'],
        'projectId': json['projectId'],
        'graphTitle': json['graphTitle'],
        'xProperty': json['xProperty'],
        'yProperty': json['yProperty'],
        'graphType': json['graphType'],
        'caption': json['caption'],
    };
}

export function CustomGraphTypeToJSON(value?: CustomGraphType | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'id': value['id'],
        'eventTypeId': value['eventTypeId'],
        'projectId': value['projectId'],
        'graphTitle': value['graphTitle'],
        'xProperty': value['xProperty'],
        'yProperty': value['yProperty'],
        'graphType': value['graphType'],
        'caption': value['caption'],
    };
}

