/* tslint:disable */
/* eslint-disable */
/**
 * Juno
 * Juno Public API Docs
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface CustomEventTypeResponse
 */
export interface CustomEventTypeResponse {
    /**
     * Event type ID
     * @type {string}
     * @memberof CustomEventTypeResponse
     */
    id: string;
    /**
     * Category
     * @type {string}
     * @memberof CustomEventTypeResponse
     */
    category: string;
    /**
     * Subcategory
     * @type {string}
     * @memberof CustomEventTypeResponse
     */
    subcategory: string;
    /**
     * Properties
     * @type {Array<string>}
     * @memberof CustomEventTypeResponse
     */
    properties: Array<string>;
    /**
     * Project ID
     * @type {string}
     * @memberof CustomEventTypeResponse
     */
    projectId: string;
}

/**
 * Check if a given object implements the CustomEventTypeResponse interface.
 */
export function instanceOfCustomEventTypeResponse(value: object): value is CustomEventTypeResponse {
    if (!('id' in value) || value['id'] === undefined) return false;
    if (!('category' in value) || value['category'] === undefined) return false;
    if (!('subcategory' in value) || value['subcategory'] === undefined) return false;
    if (!('properties' in value) || value['properties'] === undefined) return false;
    if (!('projectId' in value) || value['projectId'] === undefined) return false;
    return true;
}

export function CustomEventTypeResponseFromJSON(json: any): CustomEventTypeResponse {
    return CustomEventTypeResponseFromJSONTyped(json, false);
}

export function CustomEventTypeResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): CustomEventTypeResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'],
        'category': json['category'],
        'subcategory': json['subcategory'],
        'properties': json['properties'],
        'projectId': json['projectId'],
    };
}

export function CustomEventTypeResponseToJSON(value?: CustomEventTypeResponse | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'id': value['id'],
        'category': value['category'],
        'subcategory': value['subcategory'],
        'properties': value['properties'],
        'projectId': value['projectId'],
    };
}

