/* tslint:disable */
/* eslint-disable */
/**
 * Juno
 * Juno Public API Docs
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface CustomEventResponse
 */
export interface CustomEventResponse {
    /**
     * Event ID
     * @type {string}
     * @memberof CustomEventResponse
     */
    id: string;
    /**
     * Event type ID
     * @type {string}
     * @memberof CustomEventResponse
     */
    eventTypeId: string;
    /**
     * Project ID
     * @type {string}
     * @memberof CustomEventResponse
     */
    projectId: string;
    /**
     * Environment
     * @type {string}
     * @memberof CustomEventResponse
     */
    environment: string;
    /**
     * Created timestamp
     * @type {string}
     * @memberof CustomEventResponse
     */
    createdAt: string;
    /**
     * Updated timestamp
     * @type {string}
     * @memberof CustomEventResponse
     */
    updatedAt: string;
    /**
     * Custom properties
     * @type {object}
     * @memberof CustomEventResponse
     */
    properties: object;
}

/**
 * Check if a given object implements the CustomEventResponse interface.
 */
export function instanceOfCustomEventResponse(value: object): value is CustomEventResponse {
    if (!('id' in value) || value['id'] === undefined) return false;
    if (!('eventTypeId' in value) || value['eventTypeId'] === undefined) return false;
    if (!('projectId' in value) || value['projectId'] === undefined) return false;
    if (!('environment' in value) || value['environment'] === undefined) return false;
    if (!('createdAt' in value) || value['createdAt'] === undefined) return false;
    if (!('updatedAt' in value) || value['updatedAt'] === undefined) return false;
    if (!('properties' in value) || value['properties'] === undefined) return false;
    return true;
}

export function CustomEventResponseFromJSON(json: any): CustomEventResponse {
    return CustomEventResponseFromJSONTyped(json, false);
}

export function CustomEventResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): CustomEventResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'],
        'eventTypeId': json['eventTypeId'],
        'projectId': json['projectId'],
        'environment': json['environment'],
        'createdAt': json['createdAt'],
        'updatedAt': json['updatedAt'],
        'properties': json['properties'],
    };
}

export function CustomEventResponseToJSON(value?: CustomEventResponse | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'id': value['id'],
        'eventTypeId': value['eventTypeId'],
        'projectId': value['projectId'],
        'environment': value['environment'],
        'createdAt': value['createdAt'],
        'updatedAt': value['updatedAt'],
        'properties': value['properties'],
    };
}

