/* tslint:disable */
/* eslint-disable */
/**
 * Juno
 * Juno Public API Docs
 *
 * The version of the OpenAPI document: 1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 *
 * @export
 * @interface DeleteFilesModel
 */
export interface DeleteFilesModel {
  /**
   * Name of the bucket containing the files
   * @type {string}
   * @memberof DeleteFilesModel
   */
  bucketName: string;
  /**
   * Configuration ID for the bucket
   * @type {number}
   * @memberof DeleteFilesModel
   */
  configId: number;
  /**
   * List of file names to delete
   * @type {Array<string>}
   * @memberof DeleteFilesModel
   */
  fileNames: Array<string>;
}

/**
 * Check if a given object implements the DeleteFilesModel interface.
 */
export function instanceOfDeleteFilesModel(
  value: object
): value is DeleteFilesModel {
  if (!('bucketName' in value) || value['bucketName'] === undefined)
    return false;
  if (!('configId' in value) || value['configId'] === undefined) return false;
  if (!('fileNames' in value) || value['fileNames'] === undefined) return false;
  return true;
}

export function DeleteFilesModelFromJSON(json: any): DeleteFilesModel {
  return DeleteFilesModelFromJSONTyped(json, false);
}

export function DeleteFilesModelFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean
): DeleteFilesModel {
  if (json == null) {
    return json;
  }
  return {
    bucketName: json['bucketName'],
    configId: json['configId'],
    fileNames: json['fileNames'],
  };
}

export function DeleteFilesModelToJSON(value?: DeleteFilesModel | null): any {
  if (value == null) {
    return value;
  }
  return {
    bucketName: value['bucketName'],
    configId: value['configId'],
    fileNames: value['fileNames'],
  };
}
