/* tslint:disable */
/* eslint-disable */
/**
 * Juno
 * Juno Public API Docs
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface DownloadFileModel
 */
export interface DownloadFileModel {
    /**
     * The name of the bucket to use for downloading
     * @type {string}
     * @memberof DownloadFileModel
     */
    bucketName: string;
    /**
     * The config id of the file to use for downloading
     * @type {number}
     * @memberof DownloadFileModel
     */
    configId: number;
    /**
     * The name of the file to use for downloading
     * @type {string}
     * @memberof DownloadFileModel
     */
    fileName: string;
    /**
     * The name of the provider to connect to for downloading
     * @type {string}
     * @memberof DownloadFileModel
     */
    providerName: string;
    /**
     * The region to use for downloading
     * @type {string}
     * @memberof DownloadFileModel
     */
    region?: string;
}

/**
 * Check if a given object implements the DownloadFileModel interface.
 */
export function instanceOfDownloadFileModel(value: object): value is DownloadFileModel {
    if (!('bucketName' in value) || value['bucketName'] === undefined) return false;
    if (!('configId' in value) || value['configId'] === undefined) return false;
    if (!('fileName' in value) || value['fileName'] === undefined) return false;
    if (!('providerName' in value) || value['providerName'] === undefined) return false;
    return true;
}

export function DownloadFileModelFromJSON(json: any): DownloadFileModel {
    return DownloadFileModelFromJSONTyped(json, false);
}

export function DownloadFileModelFromJSONTyped(json: any, ignoreDiscriminator: boolean): DownloadFileModel {
    if (json == null) {
        return json;
    }
    return {
        
        'bucketName': json['bucketName'],
        'configId': json['configId'],
        'fileName': json['fileName'],
        'providerName': json['providerName'],
        'region': json['region'] == null ? undefined : json['region'],
    };
}

export function DownloadFileModelToJSON(value?: DownloadFileModel | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'bucketName': value['bucketName'],
        'configId': value['configId'],
        'fileName': value['fileName'],
        'providerName': value['providerName'],
        'region': value['region'],
    };
}

