/* tslint:disable */
/* eslint-disable */
/**
 * Juno
 * Juno Public API Docs
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface EmailSender
 */
export interface EmailSender {
    /**
     * 
     * @type {string}
     * @memberof EmailSender
     */
    username: string;
    /**
     * 
     * @type {string}
     * @memberof EmailSender
     */
    description?: string;
    /**
     * 
     * @type {string}
     * @memberof EmailSender
     */
    domain: string;
    /**
     * 
     * @type {Array<object>}
     * @memberof EmailSender
     */
    projects: Array<object>;
}

/**
 * Check if a given object implements the EmailSender interface.
 */
export function instanceOfEmailSender(value: object): value is EmailSender {
    if (!('username' in value) || value['username'] === undefined) return false;
    if (!('domain' in value) || value['domain'] === undefined) return false;
    if (!('projects' in value) || value['projects'] === undefined) return false;
    return true;
}

export function EmailSenderFromJSON(json: any): EmailSender {
    return EmailSenderFromJSONTyped(json, false);
}

export function EmailSenderFromJSONTyped(json: any, ignoreDiscriminator: boolean): EmailSender {
    if (json == null) {
        return json;
    }
    return {
        
        'username': json['username'],
        'description': json['description'] == null ? undefined : json['description'],
        'domain': json['domain'],
        'projects': json['projects'],
    };
}

export function EmailSenderToJSON(value?: EmailSender | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'username': value['username'],
        'description': value['description'],
        'domain': value['domain'],
        'projects': value['projects'],
    };
}

