/* tslint:disable */
/* eslint-disable */
/**
 * Juno
 * Juno Public API Docs
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface EmailRecipient
 */
export interface EmailRecipient {
    /**
     * Recipient email address
     * @type {string}
     * @memberof EmailRecipient
     */
    email: string;
    /**
     * Recipient name
     * @type {string}
     * @memberof EmailRecipient
     */
    name?: string;
}

/**
 * Check if a given object implements the EmailRecipient interface.
 */
export function instanceOfEmailRecipient(value: object): value is EmailRecipient {
    if (!('email' in value) || value['email'] === undefined) return false;
    return true;
}

export function EmailRecipientFromJSON(json: any): EmailRecipient {
    return EmailRecipientFromJSONTyped(json, false);
}

export function EmailRecipientFromJSONTyped(json: any, ignoreDiscriminator: boolean): EmailRecipient {
    if (json == null) {
        return json;
    }
    return {
        
        'email': json['email'],
        'name': json['name'] == null ? undefined : json['name'],
    };
}

export function EmailRecipientToJSON(value?: EmailRecipient | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'email': value['email'],
        'name': value['name'],
    };
}

