/* tslint:disable */
/* eslint-disable */
/**
 * Juno
 * Juno Public API Docs
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface EmailDomain
 */
export interface EmailDomain {
    /**
     * 
     * @type {string}
     * @memberof EmailDomain
     */
    domain: string;
    /**
     * 
     * @type {string}
     * @memberof EmailDomain
     */
    subdomain?: string;
    /**
     * 
     * @type {number}
     * @memberof EmailDomain
     */
    sendgridId: number;
    /**
     * 
     * @type {Array<object>}
     * @memberof EmailDomain
     */
    projects: Array<object>;
}

/**
 * Check if a given object implements the EmailDomain interface.
 */
export function instanceOfEmailDomain(value: object): value is EmailDomain {
    if (!('domain' in value) || value['domain'] === undefined) return false;
    if (!('sendgridId' in value) || value['sendgridId'] === undefined) return false;
    if (!('projects' in value) || value['projects'] === undefined) return false;
    return true;
}

export function EmailDomainFromJSON(json: any): EmailDomain {
    return EmailDomainFromJSONTyped(json, false);
}

export function EmailDomainFromJSONTyped(json: any, ignoreDiscriminator: boolean): EmailDomain {
    if (json == null) {
        return json;
    }
    return {
        
        'domain': json['domain'],
        'subdomain': json['subdomain'] == null ? undefined : json['subdomain'],
        'sendgridId': json['sendgridId'],
        'projects': json['projects'],
    };
}

export function EmailDomainToJSON(value?: EmailDomain | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'domain': value['domain'],
        'subdomain': value['subdomain'],
        'sendgridId': value['sendgridId'],
        'projects': value['projects'],
    };
}

