/* tslint:disable */
/* eslint-disable */
/**
 * Juno
 * Juno Public API Docs
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface EmailSenderSendEmailModel
 */
export interface EmailSenderSendEmailModel {
    /**
     * Sender email address
     * @type {string}
     * @memberof EmailSenderSendEmailModel
     */
    email: string;
    /**
     * Sender name
     * @type {string}
     * @memberof EmailSenderSendEmailModel
     */
    name?: string;
}

/**
 * Check if a given object implements the EmailSenderSendEmailModel interface.
 */
export function instanceOfEmailSenderSendEmailModel(value: object): value is EmailSenderSendEmailModel {
    if (!('email' in value) || value['email'] === undefined) return false;
    return true;
}

export function EmailSenderSendEmailModelFromJSON(json: any): EmailSenderSendEmailModel {
    return EmailSenderSendEmailModelFromJSONTyped(json, false);
}

export function EmailSenderSendEmailModelFromJSONTyped(json: any, ignoreDiscriminator: boolean): EmailSenderSendEmailModel {
    if (json == null) {
        return json;
    }
    return {
        
        'email': json['email'],
        'name': json['name'] == null ? undefined : json['name'],
    };
}

export function EmailSenderSendEmailModelToJSON(value?: EmailSenderSendEmailModel | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'email': value['email'],
        'name': value['name'],
    };
}

