/* tslint:disable */
/* eslint-disable */
/**
 * Juno
 * Juno Public API Docs
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { EmailSender } from './EmailSender';
import {
    EmailSenderFromJSON,
    EmailSenderFromJSONTyped,
    EmailSenderToJSON,
} from './EmailSender';
import type { EmailDomain } from './EmailDomain';
import {
    EmailDomainFromJSON,
    EmailDomainFromJSONTyped,
    EmailDomainToJSON,
} from './EmailDomain';

/**
 * 
 * @export
 * @interface EmailConfigResponse
 */
export interface EmailConfigResponse {
    /**
     * Email Configuration ID
     * @type {number}
     * @memberof EmailConfigResponse
     */
    id: number;
    /**
     * The configured environment
     * @type {string}
     * @memberof EmailConfigResponse
     */
    environment: string;
    /**
     * The configured sendGrid key
     * @type {string}
     * @memberof EmailConfigResponse
     */
    sendgridKey: string;
    /**
     * The list of domains associated with the email config
     * @type {Array<EmailDomain>}
     * @memberof EmailConfigResponse
     */
    domains: Array<EmailDomain>;
    /**
     * The list of senders associated with the email config
     * @type {Array<EmailSender>}
     * @memberof EmailConfigResponse
     */
    senders: Array<EmailSender>;
}

/**
 * Check if a given object implements the EmailConfigResponse interface.
 */
export function instanceOfEmailConfigResponse(value: object): value is EmailConfigResponse {
    if (!('id' in value) || value['id'] === undefined) return false;
    if (!('environment' in value) || value['environment'] === undefined) return false;
    if (!('sendgridKey' in value) || value['sendgridKey'] === undefined) return false;
    if (!('domains' in value) || value['domains'] === undefined) return false;
    if (!('senders' in value) || value['senders'] === undefined) return false;
    return true;
}

export function EmailConfigResponseFromJSON(json: any): EmailConfigResponse {
    return EmailConfigResponseFromJSONTyped(json, false);
}

export function EmailConfigResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): EmailConfigResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'],
        'environment': json['environment'],
        'sendgridKey': json['sendgridKey'],
        'domains': ((json['domains'] as Array<any>).map(EmailDomainFromJSON)),
        'senders': ((json['senders'] as Array<any>).map(EmailSenderFromJSON)),
    };
}

export function EmailConfigResponseToJSON(value?: EmailConfigResponse | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'id': value['id'],
        'environment': value['environment'],
        'sendgridKey': value['sendgridKey'],
        'domains': ((value['domains'] as Array<any>).map(EmailDomainToJSON)),
        'senders': ((value['senders'] as Array<any>).map(EmailSenderToJSON)),
    };
}

