/* tslint:disable */
/* eslint-disable */
/**
 * Juno
 * Juno Public API Docs
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface EmailContent
 */
export interface EmailContent {
    /**
     * MIME type for the content
     * @type {string}
     * @memberof EmailContent
     */
    type: string;
    /**
     * Content of the email
     * @type {string}
     * @memberof EmailContent
     */
    value: string;
}

/**
 * Check if a given object implements the EmailContent interface.
 */
export function instanceOfEmailContent(value: object): value is EmailContent {
    if (!('type' in value) || value['type'] === undefined) return false;
    if (!('value' in value) || value['value'] === undefined) return false;
    return true;
}

export function EmailContentFromJSON(json: any): EmailContent {
    return EmailContentFromJSONTyped(json, false);
}

export function EmailContentFromJSONTyped(json: any, ignoreDiscriminator: boolean): EmailContent {
    if (json == null) {
        return json;
    }
    return {
        
        'type': json['type'],
        'value': json['value'],
    };
}

export function EmailContentToJSON(value?: EmailContent | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'type': value['type'],
        'value': value['value'],
    };
}

