/* tslint:disable */
/* eslint-disable */
/**
 * Juno
 * Juno Public API Docs
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface FileProviderPartial
 */
export interface FileProviderPartial {
    /**
     * The unique provider name of the file provider
     * @type {string}
     * @memberof FileProviderPartial
     */
    providerName: string;
    /**
     * The metadata of the file provider
     * @type {string}
     * @memberof FileProviderPartial
     */
    metadata: string;
}

/**
 * Check if a given object implements the FileProviderPartial interface.
 */
export function instanceOfFileProviderPartial(value: object): value is FileProviderPartial {
    if (!('providerName' in value) || value['providerName'] === undefined) return false;
    if (!('metadata' in value) || value['metadata'] === undefined) return false;
    return true;
}

export function FileProviderPartialFromJSON(json: any): FileProviderPartial {
    return FileProviderPartialFromJSONTyped(json, false);
}

export function FileProviderPartialFromJSONTyped(json: any, ignoreDiscriminator: boolean): FileProviderPartial {
    if (json == null) {
        return json;
    }
    return {
        
        'providerName': json['providerName'],
        'metadata': json['metadata'],
    };
}

export function FileProviderPartialToJSON(value?: FileProviderPartial | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'providerName': value['providerName'],
        'metadata': value['metadata'],
    };
}

