/* tslint:disable */
/* eslint-disable */
/**
 * Juno
 * Juno Public API Docs
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { FileBucket } from './FileBucket';
import {
    FileBucketFromJSON,
    FileBucketFromJSONTyped,
    FileBucketToJSON,
} from './FileBucket';

/**
 * 
 * @export
 * @interface FileConfigResponse
 */
export interface FileConfigResponse {
    /**
     * File Configuration ID
     * @type {number}
     * @memberof FileConfigResponse
     */
    id: number;
    /**
     * The configured environment
     * @type {string}
     * @memberof FileConfigResponse
     */
    environment: string;
    /**
     * The list of files associated with the config
     * @type {Array<any>}
     * @memberof FileConfigResponse
     */
    files: Array<any>;
    /**
     * The list of buckets associated with the config
     * @type {Array<FileBucket>}
     * @memberof FileConfigResponse
     */
    buckets: Array<FileBucket>;
}

/**
 * Check if a given object implements the FileConfigResponse interface.
 */
export function instanceOfFileConfigResponse(value: object): value is FileConfigResponse {
    if (!('id' in value) || value['id'] === undefined) return false;
    if (!('environment' in value) || value['environment'] === undefined) return false;
    if (!('files' in value) || value['files'] === undefined) return false;
    if (!('buckets' in value) || value['buckets'] === undefined) return false;
    return true;
}

export function FileConfigResponseFromJSON(json: any): FileConfigResponse {
    return FileConfigResponseFromJSONTyped(json, false);
}

export function FileConfigResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): FileConfigResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'],
        'environment': json['environment'],
        'files': json['files'],
        'buckets': ((json['buckets'] as Array<any>).map(FileBucketFromJSON)),
    };
}

export function FileConfigResponseToJSON(value?: FileConfigResponse | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'id': value['id'],
        'environment': value['environment'],
        'files': value['files'],
        'buckets': ((value['buckets'] as Array<any>).map(FileBucketToJSON)),
    };
}

