/* tslint:disable */
/* eslint-disable */
/**
 * Juno
 * Juno Public API Docs
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { CustomEventResponse } from './CustomEventResponse';
import {
    CustomEventResponseFromJSON,
    CustomEventResponseFromJSONTyped,
    CustomEventResponseToJSON,
} from './CustomEventResponse';

/**
 * 
 * @export
 * @interface GetAllCustomEventsResponse
 */
export interface GetAllCustomEventsResponse {
    /**
     * All custom events
     * @type {Array<CustomEventResponse>}
     * @memberof GetAllCustomEventsResponse
     */
    events: Array<CustomEventResponse>;
}

/**
 * Check if a given object implements the GetAllCustomEventsResponse interface.
 */
export function instanceOfGetAllCustomEventsResponse(value: object): value is GetAllCustomEventsResponse {
    if (!('events' in value) || value['events'] === undefined) return false;
    return true;
}

export function GetAllCustomEventsResponseFromJSON(json: any): GetAllCustomEventsResponse {
    return GetAllCustomEventsResponseFromJSONTyped(json, false);
}

export function GetAllCustomEventsResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): GetAllCustomEventsResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'events': ((json['events'] as Array<any>).map(CustomEventResponseFromJSON)),
    };
}

export function GetAllCustomEventsResponseToJSON(value?: GetAllCustomEventsResponse | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'events': ((value['events'] as Array<any>).map(CustomEventResponseToJSON)),
    };
}

