/* tslint:disable */
/* eslint-disable */
/**
 * Juno
 * Juno Public API Docs
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { VisitEventResponse } from './VisitEventResponse';
import {
    VisitEventResponseFromJSON,
    VisitEventResponseFromJSONTyped,
    VisitEventResponseToJSON,
} from './VisitEventResponse';

/**
 * 
 * @export
 * @interface GetAllVisitEventsResponse
 */
export interface GetAllVisitEventsResponse {
    /**
     * All visit events
     * @type {Array<VisitEventResponse>}
     * @memberof GetAllVisitEventsResponse
     */
    events: Array<VisitEventResponse>;
}

/**
 * Check if a given object implements the GetAllVisitEventsResponse interface.
 */
export function instanceOfGetAllVisitEventsResponse(value: object): value is GetAllVisitEventsResponse {
    if (!('events' in value) || value['events'] === undefined) return false;
    return true;
}

export function GetAllVisitEventsResponseFromJSON(json: any): GetAllVisitEventsResponse {
    return GetAllVisitEventsResponseFromJSONTyped(json, false);
}

export function GetAllVisitEventsResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): GetAllVisitEventsResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'events': ((json['events'] as Array<any>).map(VisitEventResponseFromJSON)),
    };
}

export function GetAllVisitEventsResponseToJSON(value?: GetAllVisitEventsResponse | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'events': ((value['events'] as Array<any>).map(VisitEventResponseToJSON)),
    };
}

