/* tslint:disable */
/* eslint-disable */
/**
 * Juno
 * Juno Public API Docs
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { ClickEventResponse } from './ClickEventResponse';
import {
    ClickEventResponseFromJSON,
    ClickEventResponseFromJSONTyped,
    ClickEventResponseToJSON,
} from './ClickEventResponse';

/**
 * 
 * @export
 * @interface GetAllClickEventsResponse
 */
export interface GetAllClickEventsResponse {
    /**
     * All click events
     * @type {Array<ClickEventResponse>}
     * @memberof GetAllClickEventsResponse
     */
    events: Array<ClickEventResponse>;
}

/**
 * Check if a given object implements the GetAllClickEventsResponse interface.
 */
export function instanceOfGetAllClickEventsResponse(value: object): value is GetAllClickEventsResponse {
    if (!('events' in value) || value['events'] === undefined) return false;
    return true;
}

export function GetAllClickEventsResponseFromJSON(json: any): GetAllClickEventsResponse {
    return GetAllClickEventsResponseFromJSONTyped(json, false);
}

export function GetAllClickEventsResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): GetAllClickEventsResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'events': ((json['events'] as Array<any>).map(ClickEventResponseFromJSON)),
    };
}

export function GetAllClickEventsResponseToJSON(value?: GetAllClickEventsResponse | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'events': ((value['events'] as Array<any>).map(ClickEventResponseToJSON)),
    };
}

