/* tslint:disable */
/* eslint-disable */
/**
 * Juno
 * Juno Public API Docs
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { CustomEventTypeResponse } from './CustomEventTypeResponse';
import {
    CustomEventTypeResponseFromJSON,
    CustomEventTypeResponseFromJSONTyped,
    CustomEventTypeResponseToJSON,
} from './CustomEventTypeResponse';

/**
 * 
 * @export
 * @interface GetAllCustomEventTypeResponse
 */
export interface GetAllCustomEventTypeResponse {
    /**
     * All custom event types
     * @type {Array<CustomEventTypeResponse>}
     * @memberof GetAllCustomEventTypeResponse
     */
    eventTypes: Array<CustomEventTypeResponse>;
}

/**
 * Check if a given object implements the GetAllCustomEventTypeResponse interface.
 */
export function instanceOfGetAllCustomEventTypeResponse(value: object): value is GetAllCustomEventTypeResponse {
    if (!('eventTypes' in value) || value['eventTypes'] === undefined) return false;
    return true;
}

export function GetAllCustomEventTypeResponseFromJSON(json: any): GetAllCustomEventTypeResponse {
    return GetAllCustomEventTypeResponseFromJSONTyped(json, false);
}

export function GetAllCustomEventTypeResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): GetAllCustomEventTypeResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'eventTypes': ((json['eventTypes'] as Array<any>).map(CustomEventTypeResponseFromJSON)),
    };
}

export function GetAllCustomEventTypeResponseToJSON(value?: GetAllCustomEventTypeResponse | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'eventTypes': ((value['eventTypes'] as Array<any>).map(CustomEventTypeResponseToJSON)),
    };
}

