/* tslint:disable */
/* eslint-disable */
/**
 * Juno
 * Juno Public API Docs
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { ClickEventResponse } from './ClickEventResponse';
import {
    ClickEventResponseFromJSON,
    ClickEventResponseFromJSONTyped,
    ClickEventResponseToJSON,
} from './ClickEventResponse';

/**
 * 
 * @export
 * @interface GetClickEventsResponse
 */
export interface GetClickEventsResponse {
    /**
     * Click events
     * @type {Array<ClickEventResponse>}
     * @memberof GetClickEventsResponse
     */
    events: Array<ClickEventResponse>;
    /**
     * Pagination cursor
     * @type {string}
     * @memberof GetClickEventsResponse
     */
    afterId: string;
}

/**
 * Check if a given object implements the GetClickEventsResponse interface.
 */
export function instanceOfGetClickEventsResponse(value: object): value is GetClickEventsResponse {
    if (!('events' in value) || value['events'] === undefined) return false;
    if (!('afterId' in value) || value['afterId'] === undefined) return false;
    return true;
}

export function GetClickEventsResponseFromJSON(json: any): GetClickEventsResponse {
    return GetClickEventsResponseFromJSONTyped(json, false);
}

export function GetClickEventsResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): GetClickEventsResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'events': ((json['events'] as Array<any>).map(ClickEventResponseFromJSON)),
        'afterId': json['afterId'],
    };
}

export function GetClickEventsResponseToJSON(value?: GetClickEventsResponse | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'events': ((value['events'] as Array<any>).map(ClickEventResponseToJSON)),
        'afterId': value['afterId'],
    };
}

