/* tslint:disable */
/* eslint-disable */
/**
 * Juno
 * Juno Public API Docs
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { CustomEventResponse } from './CustomEventResponse';
import {
    CustomEventResponseFromJSON,
    CustomEventResponseFromJSONTyped,
    CustomEventResponseToJSON,
} from './CustomEventResponse';

/**
 * 
 * @export
 * @interface GetCustomEventsResponse
 */
export interface GetCustomEventsResponse {
    /**
     * Custom events
     * @type {Array<CustomEventResponse>}
     * @memberof GetCustomEventsResponse
     */
    events: Array<CustomEventResponse>;
    /**
     * Pagination cursor
     * @type {string}
     * @memberof GetCustomEventsResponse
     */
    afterId: string;
}

/**
 * Check if a given object implements the GetCustomEventsResponse interface.
 */
export function instanceOfGetCustomEventsResponse(value: object): value is GetCustomEventsResponse {
    if (!('events' in value) || value['events'] === undefined) return false;
    if (!('afterId' in value) || value['afterId'] === undefined) return false;
    return true;
}

export function GetCustomEventsResponseFromJSON(json: any): GetCustomEventsResponse {
    return GetCustomEventsResponseFromJSONTyped(json, false);
}

export function GetCustomEventsResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): GetCustomEventsResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'events': ((json['events'] as Array<any>).map(CustomEventResponseFromJSON)),
        'afterId': json['afterId'],
    };
}

export function GetCustomEventsResponseToJSON(value?: GetCustomEventsResponse | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'events': ((value['events'] as Array<any>).map(CustomEventResponseToJSON)),
        'afterId': value['afterId'],
    };
}

