/* tslint:disable */
/* eslint-disable */
/**
 * Juno
 * Juno Public API Docs
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { InputEventResponse } from './InputEventResponse';
import {
    InputEventResponseFromJSON,
    InputEventResponseFromJSONTyped,
    InputEventResponseToJSON,
} from './InputEventResponse';

/**
 * 
 * @export
 * @interface GetInputEventsResponse
 */
export interface GetInputEventsResponse {
    /**
     * Input events
     * @type {Array<InputEventResponse>}
     * @memberof GetInputEventsResponse
     */
    events: Array<InputEventResponse>;
    /**
     * Pagination cursor
     * @type {string}
     * @memberof GetInputEventsResponse
     */
    afterId: string;
}

/**
 * Check if a given object implements the GetInputEventsResponse interface.
 */
export function instanceOfGetInputEventsResponse(value: object): value is GetInputEventsResponse {
    if (!('events' in value) || value['events'] === undefined) return false;
    if (!('afterId' in value) || value['afterId'] === undefined) return false;
    return true;
}

export function GetInputEventsResponseFromJSON(json: any): GetInputEventsResponse {
    return GetInputEventsResponseFromJSONTyped(json, false);
}

export function GetInputEventsResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): GetInputEventsResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'events': ((json['events'] as Array<any>).map(InputEventResponseFromJSON)),
        'afterId': json['afterId'],
    };
}

export function GetInputEventsResponseToJSON(value?: GetInputEventsResponse | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'events': ((value['events'] as Array<any>).map(InputEventResponseToJSON)),
        'afterId': value['afterId'],
    };
}

