/* tslint:disable */
/* eslint-disable */
/**
 * Juno
 * Juno Public API Docs
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { VisitEventResponse } from './VisitEventResponse';
import {
    VisitEventResponseFromJSON,
    VisitEventResponseFromJSONTyped,
    VisitEventResponseToJSON,
} from './VisitEventResponse';

/**
 * 
 * @export
 * @interface GetVisitEventsResponse
 */
export interface GetVisitEventsResponse {
    /**
     * Visit events
     * @type {Array<VisitEventResponse>}
     * @memberof GetVisitEventsResponse
     */
    events: Array<VisitEventResponse>;
    /**
     * Pagination cursor
     * @type {string}
     * @memberof GetVisitEventsResponse
     */
    afterId: string;
}

/**
 * Check if a given object implements the GetVisitEventsResponse interface.
 */
export function instanceOfGetVisitEventsResponse(value: object): value is GetVisitEventsResponse {
    if (!('events' in value) || value['events'] === undefined) return false;
    if (!('afterId' in value) || value['afterId'] === undefined) return false;
    return true;
}

export function GetVisitEventsResponseFromJSON(json: any): GetVisitEventsResponse {
    return GetVisitEventsResponseFromJSONTyped(json, false);
}

export function GetVisitEventsResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): GetVisitEventsResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'events': ((json['events'] as Array<any>).map(VisitEventResponseFromJSON)),
        'afterId': json['afterId'],
    };
}

export function GetVisitEventsResponseToJSON(value?: GetVisitEventsResponse | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'events': ((value['events'] as Array<any>).map(VisitEventResponseToJSON)),
        'afterId': value['afterId'],
    };
}

