/* tslint:disable */
/* eslint-disable */
/**
 * Juno
 * Juno Public API Docs
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { InputEventProperties } from './InputEventProperties';
import {
    InputEventPropertiesFromJSON,
    InputEventPropertiesFromJSONTyped,
    InputEventPropertiesToJSON,
} from './InputEventProperties';

/**
 * 
 * @export
 * @interface InputEventResponse
 */
export interface InputEventResponse {
    /**
     * Event ID
     * @type {string}
     * @memberof InputEventResponse
     */
    id: string;
    /**
     * Event category
     * @type {string}
     * @memberof InputEventResponse
     */
    category: string;
    /**
     * Event subcategory
     * @type {string}
     * @memberof InputEventResponse
     */
    subcategory: string;
    /**
     * Project ID
     * @type {string}
     * @memberof InputEventResponse
     */
    projectId: string;
    /**
     * Environment
     * @type {string}
     * @memberof InputEventResponse
     */
    environment: string;
    /**
     * Created timestamp
     * @type {string}
     * @memberof InputEventResponse
     */
    createdAt: string;
    /**
     * Updated timestamp
     * @type {string}
     * @memberof InputEventResponse
     */
    updatedAt: string;
    /**
     * Event properties
     * @type {InputEventProperties}
     * @memberof InputEventResponse
     */
    eventProperties: InputEventProperties;
}

/**
 * Check if a given object implements the InputEventResponse interface.
 */
export function instanceOfInputEventResponse(value: object): value is InputEventResponse {
    if (!('id' in value) || value['id'] === undefined) return false;
    if (!('category' in value) || value['category'] === undefined) return false;
    if (!('subcategory' in value) || value['subcategory'] === undefined) return false;
    if (!('projectId' in value) || value['projectId'] === undefined) return false;
    if (!('environment' in value) || value['environment'] === undefined) return false;
    if (!('createdAt' in value) || value['createdAt'] === undefined) return false;
    if (!('updatedAt' in value) || value['updatedAt'] === undefined) return false;
    if (!('eventProperties' in value) || value['eventProperties'] === undefined) return false;
    return true;
}

export function InputEventResponseFromJSON(json: any): InputEventResponse {
    return InputEventResponseFromJSONTyped(json, false);
}

export function InputEventResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): InputEventResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'],
        'category': json['category'],
        'subcategory': json['subcategory'],
        'projectId': json['projectId'],
        'environment': json['environment'],
        'createdAt': json['createdAt'],
        'updatedAt': json['updatedAt'],
        'eventProperties': InputEventPropertiesFromJSON(json['eventProperties']),
    };
}

export function InputEventResponseToJSON(value?: InputEventResponse | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'id': value['id'],
        'category': value['category'],
        'subcategory': value['subcategory'],
        'projectId': value['projectId'],
        'environment': value['environment'],
        'createdAt': value['createdAt'],
        'updatedAt': value['updatedAt'],
        'eventProperties': InputEventPropertiesToJSON(value['eventProperties']),
    };
}

