/* tslint:disable */
/* eslint-disable */
/**
 * Juno
 * Juno Public API Docs
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface IssueApiKeyRequest
 */
export interface IssueApiKeyRequest {
    /**
     * Optional description for key
     * @type {string}
     * @memberof IssueApiKeyRequest
     */
    description?: string;
    /**
     * Environment the key will be tied to
     * @type {string}
     * @memberof IssueApiKeyRequest
     */
    environment: string;
    /**
     * Project identifier
     * @type {object}
     * @memberof IssueApiKeyRequest
     */
    project: object;
}

/**
 * Check if a given object implements the IssueApiKeyRequest interface.
 */
export function instanceOfIssueApiKeyRequest(value: object): value is IssueApiKeyRequest {
    if (!('environment' in value) || value['environment'] === undefined) return false;
    if (!('project' in value) || value['project'] === undefined) return false;
    return true;
}

export function IssueApiKeyRequestFromJSON(json: any): IssueApiKeyRequest {
    return IssueApiKeyRequestFromJSONTyped(json, false);
}

export function IssueApiKeyRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): IssueApiKeyRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'description': json['description'] == null ? undefined : json['description'],
        'environment': json['environment'],
        'project': json['project'],
    };
}

export function IssueApiKeyRequestToJSON(value?: IssueApiKeyRequest | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'description': value['description'],
        'environment': value['environment'],
        'project': value['project'],
    };
}

