/* tslint:disable */
/* eslint-disable */
/**
 * Juno
 * Juno Public API Docs
 *
 * The version of the OpenAPI document: 1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 *
 * @export
 * @interface IssueApiKeyResponse
 */
export interface IssueApiKeyResponse {
  /**
   * The generated API key value (store immediately, not retrievable again)
   * @type {string}
   * @memberof IssueApiKeyResponse
   */
  apiKey: string;
  /**
   * Environment this key was issued for
   * @type {string}
   * @memberof IssueApiKeyResponse
   */
  environment: string;
  /**
   * Description provided at creation
   * @type {string}
   * @memberof IssueApiKeyResponse
   */
  description: string;
  /**
   * ISO timestamp of key creation
   * @type {string}
   * @memberof IssueApiKeyResponse
   */
  createdAt: string;
  /**
   * project identifier for the API key
   * @type {string}
   * @memberof IssueApiKeyResponse
   */
  project: string;
}

/**
 * Check if a given object implements the IssueApiKeyResponse interface.
 */
export function instanceOfIssueApiKeyResponse(
  value: object
): value is IssueApiKeyResponse {
  if (!('apiKey' in value) || value['apiKey'] === undefined) return false;
  if (!('environment' in value) || value['environment'] === undefined)
    return false;
  if (!('description' in value) || value['description'] === undefined)
    return false;
  if (!('createdAt' in value) || value['createdAt'] === undefined) return false;
  if (!('project' in value) || value['project'] === undefined) return false;
  return true;
}

export function IssueApiKeyResponseFromJSON(json: any): IssueApiKeyResponse {
  return IssueApiKeyResponseFromJSONTyped(json, false);
}

export function IssueApiKeyResponseFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean
): IssueApiKeyResponse {
  if (json == null) {
    return json;
  }
  return {
    apiKey: json['apiKey'],
    environment: json['environment'],
    description: json['description'],
    createdAt: json['createdAt'],
    project: json['project'],
  };
}

export function IssueApiKeyResponseToJSON(
  value?: IssueApiKeyResponse | null
): any {
  if (value == null) {
    return value;
  }
  return {
    apiKey: value['apiKey'],
    environment: value['environment'],
    description: value['description'],
    createdAt: value['createdAt'],
    project: value['project'],
  };
}
