/* tslint:disable */
/* eslint-disable */
/**
 * Juno
 * Juno Public API Docs
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface IssueJWTResponse
 */
export interface IssueJWTResponse {
    /**
     * Created JWT token
     * @type {string}
     * @memberof IssueJWTResponse
     */
    token: string;
}

/**
 * Check if a given object implements the IssueJWTResponse interface.
 */
export function instanceOfIssueJWTResponse(value: object): value is IssueJWTResponse {
    if (!('token' in value) || value['token'] === undefined) return false;
    return true;
}

export function IssueJWTResponseFromJSON(json: any): IssueJWTResponse {
    return IssueJWTResponseFromJSONTyped(json, false);
}

export function IssueJWTResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): IssueJWTResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'token': json['token'],
    };
}

export function IssueJWTResponseToJSON(value?: IssueJWTResponse | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'token': value['token'],
    };
}

