/* tslint:disable */
/* eslint-disable */
/**
 * Juno
 * Juno Public API Docs
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface IssueApiKeyResponse
 */
export interface IssueApiKeyResponse {
    /**
     * The generated API key
     * @type {string}
     * @memberof IssueApiKeyResponse
     */
    apiKey: string;
}

/**
 * Check if a given object implements the IssueApiKeyResponse interface.
 */
export function instanceOfIssueApiKeyResponse(value: object): value is IssueApiKeyResponse {
    if (!('apiKey' in value) || value['apiKey'] === undefined) return false;
    return true;
}

export function IssueApiKeyResponseFromJSON(json: any): IssueApiKeyResponse {
    return IssueApiKeyResponseFromJSONTyped(json, false);
}

export function IssueApiKeyResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): IssueApiKeyResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'apiKey': json['apiKey'],
    };
}

export function IssueApiKeyResponseToJSON(value?: IssueApiKeyResponse | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'apiKey': value['apiKey'],
    };
}

