/* tslint:disable */
/* eslint-disable */
/**
 * Juno
 * Juno Public API Docs
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface LinkProjectModel
 */
export interface LinkProjectModel {
    /**
     * ID of project to be linked
     * @type {number}
     * @memberof LinkProjectModel
     */
    id?: number;
    /**
     * Name of project to be linked
     * @type {string}
     * @memberof LinkProjectModel
     */
    name?: string;
}

/**
 * Check if a given object implements the LinkProjectModel interface.
 */
export function instanceOfLinkProjectModel(value: object): value is LinkProjectModel {
    return true;
}

export function LinkProjectModelFromJSON(json: any): LinkProjectModel {
    return LinkProjectModelFromJSONTyped(json, false);
}

export function LinkProjectModelFromJSONTyped(json: any, ignoreDiscriminator: boolean): LinkProjectModel {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'] == null ? undefined : json['id'],
        'name': json['name'] == null ? undefined : json['name'],
    };
}

export function LinkProjectModelToJSON(value?: LinkProjectModel | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'id': value['id'],
        'name': value['name'],
    };
}

