/* tslint:disable */
/* eslint-disable */
/**
 * Juno
 * Juno Public API Docs
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface LinkUserModel
 */
export interface LinkUserModel {
    /**
     * The ID of the user
     * @type {number}
     * @memberof LinkUserModel
     */
    id?: number;
    /**
     * The email of the user
     * @type {string}
     * @memberof LinkUserModel
     */
    email?: string;
}

/**
 * Check if a given object implements the LinkUserModel interface.
 */
export function instanceOfLinkUserModel(value: object): value is LinkUserModel {
    return true;
}

export function LinkUserModelFromJSON(json: any): LinkUserModel {
    return LinkUserModelFromJSONTyped(json, false);
}

export function LinkUserModelFromJSONTyped(json: any, ignoreDiscriminator: boolean): LinkUserModel {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'] == null ? undefined : json['id'],
        'email': json['email'] == null ? undefined : json['email'],
    };
}

export function LinkUserModelToJSON(value?: LinkUserModel | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'id': value['id'],
        'email': value['email'],
    };
}

