/* tslint:disable */
/* eslint-disable */
/**
 * Juno
 * Juno Public API Docs
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface LogClickEventRequest
 */
export interface LogClickEventRequest {
    /**
     * The ID of the object that was clicked
     * @type {string}
     * @memberof LogClickEventRequest
     */
    objectId: string;
    /**
     * The ID of the user who performed the click
     * @type {string}
     * @memberof LogClickEventRequest
     */
    userId: string;
}

/**
 * Check if a given object implements the LogClickEventRequest interface.
 */
export function instanceOfLogClickEventRequest(value: object): value is LogClickEventRequest {
    if (!('objectId' in value) || value['objectId'] === undefined) return false;
    if (!('userId' in value) || value['userId'] === undefined) return false;
    return true;
}

export function LogClickEventRequestFromJSON(json: any): LogClickEventRequest {
    return LogClickEventRequestFromJSONTyped(json, false);
}

export function LogClickEventRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): LogClickEventRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'objectId': json['objectId'],
        'userId': json['userId'],
    };
}

export function LogClickEventRequestToJSON(value?: LogClickEventRequest | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'objectId': value['objectId'],
        'userId': value['userId'],
    };
}

