/* tslint:disable */
/* eslint-disable */
/**
 * Juno
 * Juno Public API Docs
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface LogCustomEventRequest
 */
export interface LogCustomEventRequest {
    /**
     * The category of the custom event
     * @type {string}
     * @memberof LogCustomEventRequest
     */
    category: string;
    /**
     * The subcategory of the custom event
     * @type {string}
     * @memberof LogCustomEventRequest
     */
    subcategory: string;
    /**
     * Custom properties for the event
     * @type {object}
     * @memberof LogCustomEventRequest
     */
    properties: object;
}

/**
 * Check if a given object implements the LogCustomEventRequest interface.
 */
export function instanceOfLogCustomEventRequest(value: object): value is LogCustomEventRequest {
    if (!('category' in value) || value['category'] === undefined) return false;
    if (!('subcategory' in value) || value['subcategory'] === undefined) return false;
    if (!('properties' in value) || value['properties'] === undefined) return false;
    return true;
}

export function LogCustomEventRequestFromJSON(json: any): LogCustomEventRequest {
    return LogCustomEventRequestFromJSONTyped(json, false);
}

export function LogCustomEventRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): LogCustomEventRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'category': json['category'],
        'subcategory': json['subcategory'],
        'properties': json['properties'],
    };
}

export function LogCustomEventRequestToJSON(value?: LogCustomEventRequest | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'category': value['category'],
        'subcategory': value['subcategory'],
        'properties': value['properties'],
    };
}

