/* tslint:disable */
/* eslint-disable */
/**
 * Juno
 * Juno Public API Docs
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface LogInputEventRequest
 */
export interface LogInputEventRequest {
    /**
     * The ID of the input object
     * @type {string}
     * @memberof LogInputEventRequest
     */
    objectId: string;
    /**
     * The ID of the user who interacted with the input
     * @type {string}
     * @memberof LogInputEventRequest
     */
    userId: string;
    /**
     * The text value entered in the input
     * @type {string}
     * @memberof LogInputEventRequest
     */
    textValue: string;
}

/**
 * Check if a given object implements the LogInputEventRequest interface.
 */
export function instanceOfLogInputEventRequest(value: object): value is LogInputEventRequest {
    if (!('objectId' in value) || value['objectId'] === undefined) return false;
    if (!('userId' in value) || value['userId'] === undefined) return false;
    if (!('textValue' in value) || value['textValue'] === undefined) return false;
    return true;
}

export function LogInputEventRequestFromJSON(json: any): LogInputEventRequest {
    return LogInputEventRequestFromJSONTyped(json, false);
}

export function LogInputEventRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): LogInputEventRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'objectId': json['objectId'],
        'userId': json['userId'],
        'textValue': json['textValue'],
    };
}

export function LogInputEventRequestToJSON(value?: LogInputEventRequest | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'objectId': value['objectId'],
        'userId': value['userId'],
        'textValue': value['textValue'],
    };
}

