/* tslint:disable */
/* eslint-disable */
/**
 * Juno
 * Juno Public API Docs
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface ModelFile
 */
export interface ModelFile {
    /**
     * 
     * @type {object}
     * @memberof ModelFile
     */
    fileId: object;
    /**
     * 
     * @type {string}
     * @memberof ModelFile
     */
    metadata: string;
}

/**
 * Check if a given object implements the ModelFile interface.
 */
export function instanceOfModelFile(value: object): value is ModelFile {
    if (!('fileId' in value) || value['fileId'] === undefined) return false;
    if (!('metadata' in value) || value['metadata'] === undefined) return false;
    return true;
}

export function ModelFileFromJSON(json: any): ModelFile {
    return ModelFileFromJSONTyped(json, false);
}

export function ModelFileFromJSONTyped(json: any, ignoreDiscriminator: boolean): ModelFile {
    if (json == null) {
        return json;
    }
    return {
        
        'fileId': json['fileId'],
        'metadata': json['metadata'],
    };
}

export function ModelFileToJSON(value?: ModelFile | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'fileId': value['fileId'],
        'metadata': value['metadata'],
    };
}

