/* tslint:disable */
/* eslint-disable */
/**
 * Juno
 * Juno Public API Docs
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface NewAccountRequestResponse
 */
export interface NewAccountRequestResponse {
    /**
     * Request ID
     * @type {number}
     * @memberof NewAccountRequestResponse
     */
    id: number;
    /**
     * Email
     * @type {string}
     * @memberof NewAccountRequestResponse
     */
    email: string;
    /**
     * Name
     * @type {string}
     * @memberof NewAccountRequestResponse
     */
    name: string;
    /**
     * Requested user type
     * @type {string}
     * @memberof NewAccountRequestResponse
     */
    userType: NewAccountRequestResponseUserTypeEnum;
    /**
     * Project name
     * @type {string}
     * @memberof NewAccountRequestResponse
     */
    projectName?: string;
    /**
     * Timestamp of request creation
     * @type {string}
     * @memberof NewAccountRequestResponse
     */
    createdAt: string;
}


/**
 * @export
 */
export const NewAccountRequestResponseUserTypeEnum = {
    Superadmin: 'SUPERADMIN',
    Admin: 'ADMIN',
    User: 'USER'
} as const;
export type NewAccountRequestResponseUserTypeEnum = typeof NewAccountRequestResponseUserTypeEnum[keyof typeof NewAccountRequestResponseUserTypeEnum];


/**
 * Check if a given object implements the NewAccountRequestResponse interface.
 */
export function instanceOfNewAccountRequestResponse(value: object): value is NewAccountRequestResponse {
    if (!('id' in value) || value['id'] === undefined) return false;
    if (!('email' in value) || value['email'] === undefined) return false;
    if (!('name' in value) || value['name'] === undefined) return false;
    if (!('userType' in value) || value['userType'] === undefined) return false;
    if (!('createdAt' in value) || value['createdAt'] === undefined) return false;
    return true;
}

export function NewAccountRequestResponseFromJSON(json: any): NewAccountRequestResponse {
    return NewAccountRequestResponseFromJSONTyped(json, false);
}

export function NewAccountRequestResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): NewAccountRequestResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'],
        'email': json['email'],
        'name': json['name'],
        'userType': json['userType'],
        'projectName': json['projectName'] == null ? undefined : json['projectName'],
        'createdAt': json['createdAt'],
    };
}

export function NewAccountRequestResponseToJSON(value?: NewAccountRequestResponse | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'id': value['id'],
        'email': value['email'],
        'name': value['name'],
        'userType': value['userType'],
        'projectName': value['projectName'],
        'createdAt': value['createdAt'],
    };
}

