/* tslint:disable */
/* eslint-disable */
/**
 * Juno
 * Juno Public API Docs
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { NewAccountRequestResponse } from './NewAccountRequestResponse';
import {
    NewAccountRequestResponseFromJSON,
    NewAccountRequestResponseFromJSONTyped,
    NewAccountRequestResponseToJSON,
} from './NewAccountRequestResponse';

/**
 * 
 * @export
 * @interface NewAccountRequestsResponse
 */
export interface NewAccountRequestsResponse {
    /**
     * List of new account requests
     * @type {Array<NewAccountRequestResponse>}
     * @memberof NewAccountRequestsResponse
     */
    requests: Array<NewAccountRequestResponse>;
}

/**
 * Check if a given object implements the NewAccountRequestsResponse interface.
 */
export function instanceOfNewAccountRequestsResponse(value: object): value is NewAccountRequestsResponse {
    if (!('requests' in value) || value['requests'] === undefined) return false;
    return true;
}

export function NewAccountRequestsResponseFromJSON(json: any): NewAccountRequestsResponse {
    return NewAccountRequestsResponseFromJSONTyped(json, false);
}

export function NewAccountRequestsResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): NewAccountRequestsResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'requests': ((json['requests'] as Array<any>).map(NewAccountRequestResponseFromJSON)),
    };
}

export function NewAccountRequestsResponseToJSON(value?: NewAccountRequestsResponse | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'requests': ((value['requests'] as Array<any>).map(NewAccountRequestResponseToJSON)),
    };
}

