/* tslint:disable */
/* eslint-disable */
/**
 * Juno
 * Juno Public API Docs
 *
 * The version of the OpenAPI document: 1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 *
 * @export
 * @interface PaginationParams
 */
export interface PaginationParams {
  /**
   * first page of results
   * @type {string}
   * @memberof PaginationParams
   */
  first: string;
  /**
   * previous page of results
   * @type {string}
   * @memberof PaginationParams
   */
  prev: string;
  /**
   * next page of results
   * @type {string}
   * @memberof PaginationParams
   */
  next: string;
  /**
   * last page of results
   * @type {string}
   * @memberof PaginationParams
   */
  last: string;
}

/**
 * Check if a given object implements the PaginationParams interface.
 */
export function instanceOfPaginationParams(
  value: object
): value is PaginationParams {
  if (!('first' in value) || value['first'] === undefined) return false;
  if (!('prev' in value) || value['prev'] === undefined) return false;
  if (!('next' in value) || value['next'] === undefined) return false;
  if (!('last' in value) || value['last'] === undefined) return false;
  return true;
}

export function PaginationParamsFromJSON(json: any): PaginationParams {
  return PaginationParamsFromJSONTyped(json, false);
}

export function PaginationParamsFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean
): PaginationParams {
  if (json == null) {
    return json;
  }
  return {
    first: json['first'],
    prev: json['prev'],
    next: json['next'],
    last: json['last'],
  };
}

export function PaginationParamsToJSON(value?: PaginationParams | null): any {
  if (value == null) {
    return value;
  }
  return {
    first: value['first'],
    prev: value['prev'],
    next: value['next'],
    last: value['last'],
  };
}
