/* tslint:disable */
/* eslint-disable */
/**
 * Juno
 * Juno Public API Docs
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { AccessKey } from './AccessKey';
import {
    AccessKeyFromJSON,
    AccessKeyFromJSONTyped,
    AccessKeyToJSON,
} from './AccessKey';

/**
 * 
 * @export
 * @interface RegisterFileProviderModel
 */
export interface RegisterFileProviderModel {
    /**
     * The access key to register with
     * @type {AccessKey}
     * @memberof RegisterFileProviderModel
     */
    accessKey: AccessKey;
    /**
     * The base url associated with file provider.
     * @type {string}
     * @memberof RegisterFileProviderModel
     */
    baseUrl: string;
    /**
     * The file provider name being registered.
     * @type {string}
     * @memberof RegisterFileProviderModel
     */
    providerName: string;
    /**
     * File provider type (one of S3 or AZURE)
     * @type {string}
     * @memberof RegisterFileProviderModel
     */
    type: string;
}

/**
 * Check if a given object implements the RegisterFileProviderModel interface.
 */
export function instanceOfRegisterFileProviderModel(value: object): value is RegisterFileProviderModel {
    if (!('accessKey' in value) || value['accessKey'] === undefined) return false;
    if (!('baseUrl' in value) || value['baseUrl'] === undefined) return false;
    if (!('providerName' in value) || value['providerName'] === undefined) return false;
    if (!('type' in value) || value['type'] === undefined) return false;
    return true;
}

export function RegisterFileProviderModelFromJSON(json: any): RegisterFileProviderModel {
    return RegisterFileProviderModelFromJSONTyped(json, false);
}

export function RegisterFileProviderModelFromJSONTyped(json: any, ignoreDiscriminator: boolean): RegisterFileProviderModel {
    if (json == null) {
        return json;
    }
    return {
        
        'accessKey': AccessKeyFromJSON(json['accessKey']),
        'baseUrl': json['baseUrl'],
        'providerName': json['providerName'],
        'type': json['type'],
    };
}

export function RegisterFileProviderModelToJSON(value?: RegisterFileProviderModel | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'accessKey': AccessKeyToJSON(value['accessKey']),
        'baseUrl': value['baseUrl'],
        'providerName': value['providerName'],
        'type': value['type'],
    };
}

