/* tslint:disable */
/* eslint-disable */
/**
 * Juno
 * Juno Public API Docs
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface RegisterEmailResponse
 */
export interface RegisterEmailResponse {
    /**
     * The email registered
     * @type {string}
     * @memberof RegisterEmailResponse
     */
    email: string;
}

/**
 * Check if a given object implements the RegisterEmailResponse interface.
 */
export function instanceOfRegisterEmailResponse(value: object): value is RegisterEmailResponse {
    if (!('email' in value) || value['email'] === undefined) return false;
    return true;
}

export function RegisterEmailResponseFromJSON(json: any): RegisterEmailResponse {
    return RegisterEmailResponseFromJSONTyped(json, false);
}

export function RegisterEmailResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): RegisterEmailResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'email': json['email'],
    };
}

export function RegisterEmailResponseToJSON(value?: RegisterEmailResponse | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'email': value['email'],
    };
}

