/* tslint:disable */
/* eslint-disable */
/**
 * Juno
 * Juno Public API Docs
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { SendGridDNSResponse } from './SendGridDNSResponse';
import {
    SendGridDNSResponseFromJSON,
    SendGridDNSResponseFromJSONTyped,
    SendGridDNSResponseToJSON,
} from './SendGridDNSResponse';

/**
 * 
 * @export
 * @interface RegisterDomainResponse
 */
export interface RegisterDomainResponse {
    /**
     * 
     * @type {number}
     * @memberof RegisterDomainResponse
     */
    id: number;
    /**
     * 
     * @type {string}
     * @memberof RegisterDomainResponse
     */
    valid: string;
    /**
     * 
     * @type {SendGridDNSResponse}
     * @memberof RegisterDomainResponse
     */
    records: SendGridDNSResponse;
    /**
     * 
     * @type {number}
     * @memberof RegisterDomainResponse
     */
    statusCode: number;
}

/**
 * Check if a given object implements the RegisterDomainResponse interface.
 */
export function instanceOfRegisterDomainResponse(value: object): value is RegisterDomainResponse {
    if (!('id' in value) || value['id'] === undefined) return false;
    if (!('valid' in value) || value['valid'] === undefined) return false;
    if (!('records' in value) || value['records'] === undefined) return false;
    if (!('statusCode' in value) || value['statusCode'] === undefined) return false;
    return true;
}

export function RegisterDomainResponseFromJSON(json: any): RegisterDomainResponse {
    return RegisterDomainResponseFromJSONTyped(json, false);
}

export function RegisterDomainResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): RegisterDomainResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'],
        'valid': json['valid'],
        'records': SendGridDNSResponseFromJSON(json['records']),
        'statusCode': json['statusCode'],
    };
}

export function RegisterDomainResponseToJSON(value?: RegisterDomainResponse | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'id': value['id'],
        'valid': value['valid'],
        'records': SendGridDNSResponseToJSON(value['records']),
        'statusCode': value['statusCode'],
    };
}

