/* tslint:disable */
/* eslint-disable */
/**
 * Juno
 * Juno Public API Docs
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface RequestNewAccountModel
 */
export interface RequestNewAccountModel {
    /**
     * Email for the new account
     * @type {string}
     * @memberof RequestNewAccountModel
     */
    email: string;
    /**
     * Name of the requester
     * @type {string}
     * @memberof RequestNewAccountModel
     */
    name: string;
    /**
     * Password for the new account
     * @type {string}
     * @memberof RequestNewAccountModel
     */
    password: string;
    /**
     * Requested user type / role
     * @type {string}
     * @memberof RequestNewAccountModel
     */
    userType: RequestNewAccountModelUserTypeEnum;
    /**
     * Optional project name to associate
     * @type {string}
     * @memberof RequestNewAccountModel
     */
    projectName?: string;
}


/**
 * @export
 */
export const RequestNewAccountModelUserTypeEnum = {
    Superadmin: 'SUPERADMIN',
    Admin: 'ADMIN',
    User: 'USER'
} as const;
export type RequestNewAccountModelUserTypeEnum = typeof RequestNewAccountModelUserTypeEnum[keyof typeof RequestNewAccountModelUserTypeEnum];


/**
 * Check if a given object implements the RequestNewAccountModel interface.
 */
export function instanceOfRequestNewAccountModel(value: object): value is RequestNewAccountModel {
    if (!('email' in value) || value['email'] === undefined) return false;
    if (!('name' in value) || value['name'] === undefined) return false;
    if (!('password' in value) || value['password'] === undefined) return false;
    if (!('userType' in value) || value['userType'] === undefined) return false;
    return true;
}

export function RequestNewAccountModelFromJSON(json: any): RequestNewAccountModel {
    return RequestNewAccountModelFromJSONTyped(json, false);
}

export function RequestNewAccountModelFromJSONTyped(json: any, ignoreDiscriminator: boolean): RequestNewAccountModel {
    if (json == null) {
        return json;
    }
    return {
        
        'email': json['email'],
        'name': json['name'],
        'password': json['password'],
        'userType': json['userType'],
        'projectName': json['projectName'] == null ? undefined : json['projectName'],
    };
}

export function RequestNewAccountModelToJSON(value?: RequestNewAccountModel | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'email': value['email'],
        'name': value['name'],
        'password': value['password'],
        'userType': value['userType'],
        'projectName': value['projectName'],
    };
}

