/* tslint:disable */
/* eslint-disable */
/**
 * Juno
 * Juno Public API Docs
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface SendEmailStatisticsResponse
 */
export interface SendEmailStatisticsResponse {
    /**
     * Date
     * @type {string}
     * @memberof SendEmailStatisticsResponse
     */
    date: string;
    /**
     * The number of links that were clicked in your emails.
     * @type {number}
     * @memberof SendEmailStatisticsResponse
     */
    clicks: number;
    /**
     * The number of unique recipients who clicked links in your emails.
     * @type {number}
     * @memberof SendEmailStatisticsResponse
     */
    uniqueClicks: number;
    /**
     * The total number of times your emails were opened by recipients.
     * @type {number}
     * @memberof SendEmailStatisticsResponse
     */
    opens: number;
    /**
     * The number of unique recipients who opened your emails.
     * @type {number}
     * @memberof SendEmailStatisticsResponse
     */
    uniqueOpens: number;
    /**
     * The number of emails that were not allowed to be delivered by ISPs.
     * @type {number}
     * @memberof SendEmailStatisticsResponse
     */
    blocks: number;
    /**
     * The number of emails that were dropped because of a bounce.
     * @type {number}
     * @memberof SendEmailStatisticsResponse
     */
    bounceDrops: number;
    /**
     * The number of emails that bounced instead of being delivered.
     * @type {number}
     * @memberof SendEmailStatisticsResponse
     */
    bounces: number;
    /**
     * The number of emails that temporarily could not be delivered.
     * @type {number}
     * @memberof SendEmailStatisticsResponse
     */
    deferred: number;
    /**
     * The number of emails confirmed to have been delivered.
     * @type {number}
     * @memberof SendEmailStatisticsResponse
     */
    delivered: number;
    /**
     * The number of recipients with malformed or invalid email addresses.
     * @type {number}
     * @memberof SendEmailStatisticsResponse
     */
    invalidEmails: number;
    /**
     * Requests from your website, application, or mail client via SMTP Relay or API.
     * @type {number}
     * @memberof SendEmailStatisticsResponse
     */
    processed: number;
    /**
     * The number of emails that were requested to be delivered.
     * @type {number}
     * @memberof SendEmailStatisticsResponse
     */
    requests: number;
    /**
     * The number of emails dropped due to a recipient marking your email as spam.
     * @type {number}
     * @memberof SendEmailStatisticsResponse
     */
    spamReportDrops: number;
    /**
     * The number of recipients who marked your email as spam.
     * @type {number}
     * @memberof SendEmailStatisticsResponse
     */
    spamReports: number;
    /**
     * The number of emails dropped due to a recipient unsubscribing.
     * @type {number}
     * @memberof SendEmailStatisticsResponse
     */
    unsubscribeDrops: number;
    /**
     * The number of recipients who unsubscribed from your emails.
     * @type {number}
     * @memberof SendEmailStatisticsResponse
     */
    unsubscribes: number;
}

/**
 * Check if a given object implements the SendEmailStatisticsResponse interface.
 */
export function instanceOfSendEmailStatisticsResponse(value: object): value is SendEmailStatisticsResponse {
    if (!('date' in value) || value['date'] === undefined) return false;
    if (!('clicks' in value) || value['clicks'] === undefined) return false;
    if (!('uniqueClicks' in value) || value['uniqueClicks'] === undefined) return false;
    if (!('opens' in value) || value['opens'] === undefined) return false;
    if (!('uniqueOpens' in value) || value['uniqueOpens'] === undefined) return false;
    if (!('blocks' in value) || value['blocks'] === undefined) return false;
    if (!('bounceDrops' in value) || value['bounceDrops'] === undefined) return false;
    if (!('bounces' in value) || value['bounces'] === undefined) return false;
    if (!('deferred' in value) || value['deferred'] === undefined) return false;
    if (!('delivered' in value) || value['delivered'] === undefined) return false;
    if (!('invalidEmails' in value) || value['invalidEmails'] === undefined) return false;
    if (!('processed' in value) || value['processed'] === undefined) return false;
    if (!('requests' in value) || value['requests'] === undefined) return false;
    if (!('spamReportDrops' in value) || value['spamReportDrops'] === undefined) return false;
    if (!('spamReports' in value) || value['spamReports'] === undefined) return false;
    if (!('unsubscribeDrops' in value) || value['unsubscribeDrops'] === undefined) return false;
    if (!('unsubscribes' in value) || value['unsubscribes'] === undefined) return false;
    return true;
}

export function SendEmailStatisticsResponseFromJSON(json: any): SendEmailStatisticsResponse {
    return SendEmailStatisticsResponseFromJSONTyped(json, false);
}

export function SendEmailStatisticsResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): SendEmailStatisticsResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'date': json['date'],
        'clicks': json['clicks'],
        'uniqueClicks': json['unique_clicks'],
        'opens': json['opens'],
        'uniqueOpens': json['unique_opens'],
        'blocks': json['blocks'],
        'bounceDrops': json['bounce_drops'],
        'bounces': json['bounces'],
        'deferred': json['deferred'],
        'delivered': json['delivered'],
        'invalidEmails': json['invalid_emails'],
        'processed': json['processed'],
        'requests': json['requests'],
        'spamReportDrops': json['spam_report_drops'],
        'spamReports': json['spam_reports'],
        'unsubscribeDrops': json['unsubscribe_drops'],
        'unsubscribes': json['unsubscribes'],
    };
}

export function SendEmailStatisticsResponseToJSON(value?: SendEmailStatisticsResponse | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'date': value['date'],
        'clicks': value['clicks'],
        'unique_clicks': value['uniqueClicks'],
        'opens': value['opens'],
        'unique_opens': value['uniqueOpens'],
        'blocks': value['blocks'],
        'bounce_drops': value['bounceDrops'],
        'bounces': value['bounces'],
        'deferred': value['deferred'],
        'delivered': value['delivered'],
        'invalid_emails': value['invalidEmails'],
        'processed': value['processed'],
        'requests': value['requests'],
        'spam_report_drops': value['spamReportDrops'],
        'spam_reports': value['spamReports'],
        'unsubscribe_drops': value['unsubscribeDrops'],
        'unsubscribes': value['unsubscribes'],
    };
}

