/* tslint:disable */
/* eslint-disable */
/**
 * Juno
 * Juno Public API Docs
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface SendEmailResponse
 */
export interface SendEmailResponse {
    /**
     * Whether an email was successfully sent
     * @type {boolean}
     * @memberof SendEmailResponse
     */
    success: boolean;
}

/**
 * Check if a given object implements the SendEmailResponse interface.
 */
export function instanceOfSendEmailResponse(value: object): value is SendEmailResponse {
    if (!('success' in value) || value['success'] === undefined) return false;
    return true;
}

export function SendEmailResponseFromJSON(json: any): SendEmailResponse {
    return SendEmailResponseFromJSONTyped(json, false);
}

export function SendEmailResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): SendEmailResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'success': json['success'],
    };
}

export function SendEmailResponseToJSON(value?: SendEmailResponse | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'success': value['success'],
    };
}

