/* tslint:disable */
/* eslint-disable */
/**
 * Juno
 * Juno Public API Docs
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { SendGridDNSRecord } from './SendGridDNSRecord';
import {
    SendGridDNSRecordFromJSON,
    SendGridDNSRecordFromJSONTyped,
    SendGridDNSRecordToJSON,
} from './SendGridDNSRecord';

/**
 * 
 * @export
 * @interface SendGridDNSResponse
 */
export interface SendGridDNSResponse {
    /**
     * 
     * @type {SendGridDNSRecord}
     * @memberof SendGridDNSResponse
     */
    mailCname: SendGridDNSRecord;
    /**
     * 
     * @type {SendGridDNSRecord}
     * @memberof SendGridDNSResponse
     */
    dkim1: SendGridDNSRecord;
    /**
     * 
     * @type {SendGridDNSRecord}
     * @memberof SendGridDNSResponse
     */
    dkim2: SendGridDNSRecord;
}

/**
 * Check if a given object implements the SendGridDNSResponse interface.
 */
export function instanceOfSendGridDNSResponse(value: object): value is SendGridDNSResponse {
    if (!('mailCname' in value) || value['mailCname'] === undefined) return false;
    if (!('dkim1' in value) || value['dkim1'] === undefined) return false;
    if (!('dkim2' in value) || value['dkim2'] === undefined) return false;
    return true;
}

export function SendGridDNSResponseFromJSON(json: any): SendGridDNSResponse {
    return SendGridDNSResponseFromJSONTyped(json, false);
}

export function SendGridDNSResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): SendGridDNSResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'mailCname': SendGridDNSRecordFromJSON(json['mail_cname']),
        'dkim1': SendGridDNSRecordFromJSON(json['dkim1']),
        'dkim2': SendGridDNSRecordFromJSON(json['dkim2']),
    };
}

export function SendGridDNSResponseToJSON(value?: SendGridDNSResponse | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'mail_cname': SendGridDNSRecordToJSON(value['mailCname']),
        'dkim1': SendGridDNSRecordToJSON(value['dkim1']),
        'dkim2': SendGridDNSRecordToJSON(value['dkim2']),
    };
}

