/* tslint:disable */
/* eslint-disable */
/**
 * Juno
 * Juno Public API Docs
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface SetupEmailResponse
 */
export interface SetupEmailResponse {
    /**
     * Whether an email was successfully setup
     * @type {boolean}
     * @memberof SetupEmailResponse
     */
    success: boolean;
}

/**
 * Check if a given object implements the SetupEmailResponse interface.
 */
export function instanceOfSetupEmailResponse(value: object): value is SetupEmailResponse {
    if (!('success' in value) || value['success'] === undefined) return false;
    return true;
}

export function SetupEmailResponseFromJSON(json: any): SetupEmailResponse {
    return SetupEmailResponseFromJSONTyped(json, false);
}

export function SetupEmailResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): SetupEmailResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'success': json['success'],
    };
}

export function SetupEmailResponseToJSON(value?: SetupEmailResponse | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'success': value['success'],
    };
}

