/* tslint:disable */
/* eslint-disable */
/**
 * Juno
 * Juno Public API Docs
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface SetupFileServiceResponse
 */
export interface SetupFileServiceResponse {
    /**
     * Whether file services were successfully setup
     * @type {boolean}
     * @memberof SetupFileServiceResponse
     */
    success: boolean;
}

/**
 * Check if a given object implements the SetupFileServiceResponse interface.
 */
export function instanceOfSetupFileServiceResponse(value: object): value is SetupFileServiceResponse {
    if (!('success' in value) || value['success'] === undefined) return false;
    return true;
}

export function SetupFileServiceResponseFromJSON(json: any): SetupFileServiceResponse {
    return SetupFileServiceResponseFromJSONTyped(json, false);
}

export function SetupFileServiceResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): SetupFileServiceResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'success': json['success'],
    };
}

export function SetupFileServiceResponseToJSON(value?: SetupFileServiceResponse | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'success': value['success'],
    };
}

