/* tslint:disable */
/* eslint-disable */
/**
 * Juno
 * Juno Public API Docs
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface UnlinkProjectModel
 */
export interface UnlinkProjectModel {
    /**
     * ID of project to be unlinked
     * @type {number}
     * @memberof UnlinkProjectModel
     */
    id?: number;
    /**
     * Name of project to be unlinked
     * @type {string}
     * @memberof UnlinkProjectModel
     */
    name?: string;
}

/**
 * Check if a given object implements the UnlinkProjectModel interface.
 */
export function instanceOfUnlinkProjectModel(value: object): value is UnlinkProjectModel {
    return true;
}

export function UnlinkProjectModelFromJSON(json: any): UnlinkProjectModel {
    return UnlinkProjectModelFromJSONTyped(json, false);
}

export function UnlinkProjectModelFromJSONTyped(json: any, ignoreDiscriminator: boolean): UnlinkProjectModel {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'] == null ? undefined : json['id'],
        'name': json['name'] == null ? undefined : json['name'],
    };
}

export function UnlinkProjectModelToJSON(value?: UnlinkProjectModel | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'id': value['id'],
        'name': value['name'],
    };
}

