/* tslint:disable */
/* eslint-disable */
/**
 * Juno
 * Juno Public API Docs
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface UploadFileModel
 */
export interface UploadFileModel {
    /**
     * Name of file
     * @type {string}
     * @memberof UploadFileModel
     */
    fileName: string;
    /**
     * Name of bucket.
     * @type {string}
     * @memberof UploadFileModel
     */
    bucketName: string;
    /**
     * Name of file provider
     * @type {string}
     * @memberof UploadFileModel
     */
    providerName: string;
    /**
     * File's configId
     * @type {number}
     * @memberof UploadFileModel
     */
    configId: number;
    /**
     * File provider's region
     * @type {string}
     * @memberof UploadFileModel
     */
    region?: string;
}

/**
 * Check if a given object implements the UploadFileModel interface.
 */
export function instanceOfUploadFileModel(value: object): value is UploadFileModel {
    if (!('fileName' in value) || value['fileName'] === undefined) return false;
    if (!('bucketName' in value) || value['bucketName'] === undefined) return false;
    if (!('providerName' in value) || value['providerName'] === undefined) return false;
    if (!('configId' in value) || value['configId'] === undefined) return false;
    return true;
}

export function UploadFileModelFromJSON(json: any): UploadFileModel {
    return UploadFileModelFromJSONTyped(json, false);
}

export function UploadFileModelFromJSONTyped(json: any, ignoreDiscriminator: boolean): UploadFileModel {
    if (json == null) {
        return json;
    }
    return {
        
        'fileName': json['fileName'],
        'bucketName': json['bucketName'],
        'providerName': json['providerName'],
        'configId': json['configId'],
        'region': json['region'] == null ? undefined : json['region'],
    };
}

export function UploadFileModelToJSON(value?: UploadFileModel | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'fileName': value['fileName'],
        'bucketName': value['bucketName'],
        'providerName': value['providerName'],
        'configId': value['configId'],
        'region': value['region'],
    };
}

