/* tslint:disable */
/* eslint-disable */
/**
 * Juno
 * Juno Public API Docs
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface UserResponse
 */
export interface UserResponse {
    /**
     * User id
     * @type {number}
     * @memberof UserResponse
     */
    id: number;
    /**
     * User email
     * @type {string}
     * @memberof UserResponse
     */
    email: string;
    /**
     * User name
     * @type {string}
     * @memberof UserResponse
     */
    name: string;
    /**
     * User type
     * @type {number}
     * @memberof UserResponse
     */
    type: UserResponseTypeEnum;
    /**
     * Project IDs associated with user
     * @type {Array<number>}
     * @memberof UserResponse
     */
    projectIds: Array<number>;
}


/**
 * @export
 */
export const UserResponseTypeEnum = {
    NUMBER_0: 0,
    NUMBER_1: 1,
    NUMBER_2: 2,
    NUMBER_MINUS_1: -1
} as const;
export type UserResponseTypeEnum = typeof UserResponseTypeEnum[keyof typeof UserResponseTypeEnum];


/**
 * Check if a given object implements the UserResponse interface.
 */
export function instanceOfUserResponse(value: object): value is UserResponse {
    if (!('id' in value) || value['id'] === undefined) return false;
    if (!('email' in value) || value['email'] === undefined) return false;
    if (!('name' in value) || value['name'] === undefined) return false;
    if (!('type' in value) || value['type'] === undefined) return false;
    if (!('projectIds' in value) || value['projectIds'] === undefined) return false;
    return true;
}

export function UserResponseFromJSON(json: any): UserResponse {
    return UserResponseFromJSONTyped(json, false);
}

export function UserResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): UserResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'],
        'email': json['email'],
        'name': json['name'],
        'type': json['type'],
        'projectIds': json['projectIds'],
    };
}

export function UserResponseToJSON(value?: UserResponse | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'id': value['id'],
        'email': value['email'],
        'name': value['name'],
        'type': value['type'],
        'projectIds': value['projectIds'],
    };
}

