/* tslint:disable */
/* eslint-disable */
/**
 * Juno
 * Juno Public API Docs
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface VisitEventProperties
 */
export interface VisitEventProperties {
    /**
     * Page URL
     * @type {string}
     * @memberof VisitEventProperties
     */
    pageUrl: string;
    /**
     * User ID
     * @type {string}
     * @memberof VisitEventProperties
     */
    userId: string;
}

/**
 * Check if a given object implements the VisitEventProperties interface.
 */
export function instanceOfVisitEventProperties(value: object): value is VisitEventProperties {
    if (!('pageUrl' in value) || value['pageUrl'] === undefined) return false;
    if (!('userId' in value) || value['userId'] === undefined) return false;
    return true;
}

export function VisitEventPropertiesFromJSON(json: any): VisitEventProperties {
    return VisitEventPropertiesFromJSONTyped(json, false);
}

export function VisitEventPropertiesFromJSONTyped(json: any, ignoreDiscriminator: boolean): VisitEventProperties {
    if (json == null) {
        return json;
    }
    return {
        
        'pageUrl': json['pageUrl'],
        'userId': json['userId'],
    };
}

export function VisitEventPropertiesToJSON(value?: VisitEventProperties | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'pageUrl': value['pageUrl'],
        'userId': value['userId'],
    };
}

