/* tslint:disable */
/* eslint-disable */
/**
 * Juno
 * Juno Public API Docs
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { VisitEventProperties } from './VisitEventProperties';
import {
    VisitEventPropertiesFromJSON,
    VisitEventPropertiesFromJSONTyped,
    VisitEventPropertiesToJSON,
} from './VisitEventProperties';

/**
 * 
 * @export
 * @interface VisitEventResponse
 */
export interface VisitEventResponse {
    /**
     * Event ID
     * @type {string}
     * @memberof VisitEventResponse
     */
    id: string;
    /**
     * Event category
     * @type {string}
     * @memberof VisitEventResponse
     */
    category: string;
    /**
     * Event subcategory
     * @type {string}
     * @memberof VisitEventResponse
     */
    subcategory: string;
    /**
     * Project ID
     * @type {string}
     * @memberof VisitEventResponse
     */
    projectId: string;
    /**
     * Environment
     * @type {string}
     * @memberof VisitEventResponse
     */
    environment: string;
    /**
     * Created timestamp
     * @type {string}
     * @memberof VisitEventResponse
     */
    createdAt: string;
    /**
     * Updated timestamp
     * @type {string}
     * @memberof VisitEventResponse
     */
    updatedAt: string;
    /**
     * Event properties
     * @type {VisitEventProperties}
     * @memberof VisitEventResponse
     */
    eventProperties: VisitEventProperties;
}

/**
 * Check if a given object implements the VisitEventResponse interface.
 */
export function instanceOfVisitEventResponse(value: object): value is VisitEventResponse {
    if (!('id' in value) || value['id'] === undefined) return false;
    if (!('category' in value) || value['category'] === undefined) return false;
    if (!('subcategory' in value) || value['subcategory'] === undefined) return false;
    if (!('projectId' in value) || value['projectId'] === undefined) return false;
    if (!('environment' in value) || value['environment'] === undefined) return false;
    if (!('createdAt' in value) || value['createdAt'] === undefined) return false;
    if (!('updatedAt' in value) || value['updatedAt'] === undefined) return false;
    if (!('eventProperties' in value) || value['eventProperties'] === undefined) return false;
    return true;
}

export function VisitEventResponseFromJSON(json: any): VisitEventResponse {
    return VisitEventResponseFromJSONTyped(json, false);
}

export function VisitEventResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): VisitEventResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'],
        'category': json['category'],
        'subcategory': json['subcategory'],
        'projectId': json['projectId'],
        'environment': json['environment'],
        'createdAt': json['createdAt'],
        'updatedAt': json['updatedAt'],
        'eventProperties': VisitEventPropertiesFromJSON(json['eventProperties']),
    };
}

export function VisitEventResponseToJSON(value?: VisitEventResponse | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'id': value['id'],
        'category': value['category'],
        'subcategory': value['subcategory'],
        'projectId': value['projectId'],
        'environment': value['environment'],
        'createdAt': value['createdAt'],
        'updatedAt': value['updatedAt'],
        'eventProperties': VisitEventPropertiesToJSON(value['eventProperties']),
    };
}

