/* tslint:disable */
/* eslint-disable */
/**
 * Juno
 * Juno Public API Docs
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import type {
  AnalyticsConfigResponse,
  CreateAnalyticsConfigModel,
  UpdateAnalyticsConfigModel,
} from '../models/index';
import {
    AnalyticsConfigResponseFromJSON,
    AnalyticsConfigResponseToJSON,
    CreateAnalyticsConfigModelFromJSON,
    CreateAnalyticsConfigModelToJSON,
    UpdateAnalyticsConfigModelFromJSON,
    UpdateAnalyticsConfigModelToJSON,
} from '../models/index';

export interface AnalyticsConfigControllerCreateAnalyticsConfigRequest {
    createAnalyticsConfigModel: CreateAnalyticsConfigModel;
}

export interface AnalyticsConfigControllerDeleteAnalyticsConfigRequest {
    projectId: string;
}

export interface AnalyticsConfigControllerGetAnalyticsConfigRequest {
    projectId: string;
}

export interface AnalyticsConfigControllerUpdateAnalyticsConfigRequest {
    projectId: string;
    updateAnalyticsConfigModel: UpdateAnalyticsConfigModel;
}

/**
 * 
 */
export class AnalyticsConfigApi extends runtime.BaseAPI {

    /**
     * Create analytics configuration
     */
    async analyticsConfigControllerCreateAnalyticsConfigRaw(requestParameters: AnalyticsConfigControllerCreateAnalyticsConfigRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<AnalyticsConfigResponse>> {
        if (requestParameters['createAnalyticsConfigModel'] == null) {
            throw new runtime.RequiredError(
                'createAnalyticsConfigModel',
                'Required parameter "createAnalyticsConfigModel" was null or undefined when calling analyticsConfigControllerCreateAnalyticsConfig().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("API_Key", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }
        const response = await this.request({
            path: `/analytics/config`,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: CreateAnalyticsConfigModelToJSON(requestParameters['createAnalyticsConfigModel']),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => AnalyticsConfigResponseFromJSON(jsonValue));
    }

    /**
     * Create analytics configuration
     */
    async analyticsConfigControllerCreateAnalyticsConfig(requestParameters: AnalyticsConfigControllerCreateAnalyticsConfigRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<AnalyticsConfigResponse> {
        const response = await this.analyticsConfigControllerCreateAnalyticsConfigRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Delete analytics configuration
     */
    async analyticsConfigControllerDeleteAnalyticsConfigRaw(requestParameters: AnalyticsConfigControllerDeleteAnalyticsConfigRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<AnalyticsConfigResponse>> {
        if (requestParameters['projectId'] == null) {
            throw new runtime.RequiredError(
                'projectId',
                'Required parameter "projectId" was null or undefined when calling analyticsConfigControllerDeleteAnalyticsConfig().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("API_Key", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }
        const response = await this.request({
            path: `/analytics/config/{projectId}`.replace(`{${"projectId"}}`, encodeURIComponent(String(requestParameters['projectId']))),
            method: 'DELETE',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => AnalyticsConfigResponseFromJSON(jsonValue));
    }

    /**
     * Delete analytics configuration
     */
    async analyticsConfigControllerDeleteAnalyticsConfig(requestParameters: AnalyticsConfigControllerDeleteAnalyticsConfigRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<AnalyticsConfigResponse> {
        const response = await this.analyticsConfigControllerDeleteAnalyticsConfigRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Get analytics configuration
     */
    async analyticsConfigControllerGetAnalyticsConfigRaw(requestParameters: AnalyticsConfigControllerGetAnalyticsConfigRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<AnalyticsConfigResponse>> {
        if (requestParameters['projectId'] == null) {
            throw new runtime.RequiredError(
                'projectId',
                'Required parameter "projectId" was null or undefined when calling analyticsConfigControllerGetAnalyticsConfig().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("API_Key", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }
        const response = await this.request({
            path: `/analytics/config/{projectId}`.replace(`{${"projectId"}}`, encodeURIComponent(String(requestParameters['projectId']))),
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => AnalyticsConfigResponseFromJSON(jsonValue));
    }

    /**
     * Get analytics configuration
     */
    async analyticsConfigControllerGetAnalyticsConfig(requestParameters: AnalyticsConfigControllerGetAnalyticsConfigRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<AnalyticsConfigResponse> {
        const response = await this.analyticsConfigControllerGetAnalyticsConfigRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Update analytics configuration
     */
    async analyticsConfigControllerUpdateAnalyticsConfigRaw(requestParameters: AnalyticsConfigControllerUpdateAnalyticsConfigRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<AnalyticsConfigResponse>> {
        if (requestParameters['projectId'] == null) {
            throw new runtime.RequiredError(
                'projectId',
                'Required parameter "projectId" was null or undefined when calling analyticsConfigControllerUpdateAnalyticsConfig().'
            );
        }

        if (requestParameters['updateAnalyticsConfigModel'] == null) {
            throw new runtime.RequiredError(
                'updateAnalyticsConfigModel',
                'Required parameter "updateAnalyticsConfigModel" was null or undefined when calling analyticsConfigControllerUpdateAnalyticsConfig().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("API_Key", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }
        const response = await this.request({
            path: `/analytics/config/{projectId}`.replace(`{${"projectId"}}`, encodeURIComponent(String(requestParameters['projectId']))),
            method: 'PUT',
            headers: headerParameters,
            query: queryParameters,
            body: UpdateAnalyticsConfigModelToJSON(requestParameters['updateAnalyticsConfigModel']),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => AnalyticsConfigResponseFromJSON(jsonValue));
    }

    /**
     * Update analytics configuration
     */
    async analyticsConfigControllerUpdateAnalyticsConfig(requestParameters: AnalyticsConfigControllerUpdateAnalyticsConfigRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<AnalyticsConfigResponse> {
        const response = await this.analyticsConfigControllerUpdateAnalyticsConfigRaw(requestParameters, initOverrides);
        return await response.value();
    }

}
