/* tslint:disable */
/* eslint-disable */
/**
 * Juno
 * Juno Public API Docs
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import type {
  ClickEventResponse,
  CustomEventResponse,
  CustomGraphTypeResponse,
  GetAllClickEventsResponse,
  GetAllCustomEventTypeResponse,
  GetAllCustomEventsResponse,
  GetAllInputEventsResponse,
  GetAllVisitEventsResponse,
  GetClickEventsResponse,
  GetCustomEventsResponse,
  GetInputEventsResponse,
  GetVisitEventsResponse,
  InputEventResponse,
  LogClickEventRequest,
  LogCustomEventRequest,
  LogInputEventRequest,
  LogVisitEventRequest,
  VisitEventResponse,
} from '../models/index';
import {
    ClickEventResponseFromJSON,
    ClickEventResponseToJSON,
    CustomEventResponseFromJSON,
    CustomEventResponseToJSON,
    CustomGraphTypeResponseFromJSON,
    CustomGraphTypeResponseToJSON,
    GetAllClickEventsResponseFromJSON,
    GetAllClickEventsResponseToJSON,
    GetAllCustomEventTypeResponseFromJSON,
    GetAllCustomEventTypeResponseToJSON,
    GetAllCustomEventsResponseFromJSON,
    GetAllCustomEventsResponseToJSON,
    GetAllInputEventsResponseFromJSON,
    GetAllInputEventsResponseToJSON,
    GetAllVisitEventsResponseFromJSON,
    GetAllVisitEventsResponseToJSON,
    GetClickEventsResponseFromJSON,
    GetClickEventsResponseToJSON,
    GetCustomEventsResponseFromJSON,
    GetCustomEventsResponseToJSON,
    GetInputEventsResponseFromJSON,
    GetInputEventsResponseToJSON,
    GetVisitEventsResponseFromJSON,
    GetVisitEventsResponseToJSON,
    InputEventResponseFromJSON,
    InputEventResponseToJSON,
    LogClickEventRequestFromJSON,
    LogClickEventRequestToJSON,
    LogCustomEventRequestFromJSON,
    LogCustomEventRequestToJSON,
    LogInputEventRequestFromJSON,
    LogInputEventRequestToJSON,
    LogVisitEventRequestFromJSON,
    LogVisitEventRequestToJSON,
    VisitEventResponseFromJSON,
    VisitEventResponseToJSON,
} from '../models/index';

export interface AnalyticsControllerGetAllClickEventsRequest {
    projectName: string;
    afterTime?: string;
    limit?: number;
}

export interface AnalyticsControllerGetAllCustomEventsRequest {
    projectName: string;
    category: string;
    subcategory: string;
    afterTime?: string;
    limit?: number;
}

export interface AnalyticsControllerGetAllInputEventsRequest {
    projectName: string;
    afterTime?: string;
    limit?: number;
}

export interface AnalyticsControllerGetAllVisitEventsRequest {
    projectName: string;
    afterTime?: string;
    limit?: number;
}

export interface AnalyticsControllerGetClickEventsPaginatedRequest {
    projectName: string;
    afterId?: string;
    environment?: string;
    limit?: number;
    afterTime?: string;
}

export interface AnalyticsControllerGetCustomEventTypesRequest {
    projectName: string;
}

export interface AnalyticsControllerGetCustomEventsPaginatedRequest {
    projectName: string;
    category: string;
    subcategory: string;
    afterId?: string;
    environment?: string;
    limit?: number;
    afterTime?: string;
}

export interface AnalyticsControllerGetCustomGraphTypesByIdRequest {
    projectName: string;
    eventTypeId: string;
}

export interface AnalyticsControllerGetInputEventsPaginatedRequest {
    projectName: string;
    afterId?: string;
    environment?: string;
    limit?: number;
    afterTime?: string;
}

export interface AnalyticsControllerGetVisitEventsPaginatedRequest {
    projectName: string;
    afterId?: string;
    environment?: string;
    limit?: number;
    afterTime?: string;
}

export interface AnalyticsControllerLogClickEventRequest {
    logClickEventRequest: LogClickEventRequest;
}

export interface AnalyticsControllerLogCustomEventRequest {
    logCustomEventRequest: LogCustomEventRequest;
}

export interface AnalyticsControllerLogInputEventRequest {
    logInputEventRequest: LogInputEventRequest;
}

export interface AnalyticsControllerLogVisitEventRequest {
    logVisitEventRequest: LogVisitEventRequest;
}

/**
 * 
 */
export class AnalyticsApi extends runtime.BaseAPI {

    /**
     * Get all click events
     */
    async analyticsControllerGetAllClickEventsRaw(requestParameters: AnalyticsControllerGetAllClickEventsRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<GetAllClickEventsResponse>> {
        if (requestParameters['projectName'] == null) {
            throw new runtime.RequiredError(
                'projectName',
                'Required parameter "projectName" was null or undefined when calling analyticsControllerGetAllClickEvents().'
            );
        }

        const queryParameters: any = {};

        if (requestParameters['projectName'] != null) {
            queryParameters['projectName'] = requestParameters['projectName'];
        }

        if (requestParameters['afterTime'] != null) {
            queryParameters['afterTime'] = requestParameters['afterTime'];
        }

        if (requestParameters['limit'] != null) {
            queryParameters['limit'] = requestParameters['limit'];
        }

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("API_Key", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }
        const response = await this.request({
            path: `/analytics/events/click/all`,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => GetAllClickEventsResponseFromJSON(jsonValue));
    }

    /**
     * Get all click events
     */
    async analyticsControllerGetAllClickEvents(requestParameters: AnalyticsControllerGetAllClickEventsRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<GetAllClickEventsResponse> {
        const response = await this.analyticsControllerGetAllClickEventsRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Get all custom events
     */
    async analyticsControllerGetAllCustomEventsRaw(requestParameters: AnalyticsControllerGetAllCustomEventsRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<GetAllCustomEventsResponse>> {
        if (requestParameters['projectName'] == null) {
            throw new runtime.RequiredError(
                'projectName',
                'Required parameter "projectName" was null or undefined when calling analyticsControllerGetAllCustomEvents().'
            );
        }

        if (requestParameters['category'] == null) {
            throw new runtime.RequiredError(
                'category',
                'Required parameter "category" was null or undefined when calling analyticsControllerGetAllCustomEvents().'
            );
        }

        if (requestParameters['subcategory'] == null) {
            throw new runtime.RequiredError(
                'subcategory',
                'Required parameter "subcategory" was null or undefined when calling analyticsControllerGetAllCustomEvents().'
            );
        }

        const queryParameters: any = {};

        if (requestParameters['projectName'] != null) {
            queryParameters['projectName'] = requestParameters['projectName'];
        }

        if (requestParameters['afterTime'] != null) {
            queryParameters['afterTime'] = requestParameters['afterTime'];
        }

        if (requestParameters['limit'] != null) {
            queryParameters['limit'] = requestParameters['limit'];
        }

        if (requestParameters['category'] != null) {
            queryParameters['category'] = requestParameters['category'];
        }

        if (requestParameters['subcategory'] != null) {
            queryParameters['subcategory'] = requestParameters['subcategory'];
        }

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("API_Key", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }
        const response = await this.request({
            path: `/analytics/events/custom/all`,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => GetAllCustomEventsResponseFromJSON(jsonValue));
    }

    /**
     * Get all custom events
     */
    async analyticsControllerGetAllCustomEvents(requestParameters: AnalyticsControllerGetAllCustomEventsRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<GetAllCustomEventsResponse> {
        const response = await this.analyticsControllerGetAllCustomEventsRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Get all input events
     */
    async analyticsControllerGetAllInputEventsRaw(requestParameters: AnalyticsControllerGetAllInputEventsRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<GetAllInputEventsResponse>> {
        if (requestParameters['projectName'] == null) {
            throw new runtime.RequiredError(
                'projectName',
                'Required parameter "projectName" was null or undefined when calling analyticsControllerGetAllInputEvents().'
            );
        }

        const queryParameters: any = {};

        if (requestParameters['projectName'] != null) {
            queryParameters['projectName'] = requestParameters['projectName'];
        }

        if (requestParameters['afterTime'] != null) {
            queryParameters['afterTime'] = requestParameters['afterTime'];
        }

        if (requestParameters['limit'] != null) {
            queryParameters['limit'] = requestParameters['limit'];
        }

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("API_Key", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }
        const response = await this.request({
            path: `/analytics/events/input/all`,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => GetAllInputEventsResponseFromJSON(jsonValue));
    }

    /**
     * Get all input events
     */
    async analyticsControllerGetAllInputEvents(requestParameters: AnalyticsControllerGetAllInputEventsRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<GetAllInputEventsResponse> {
        const response = await this.analyticsControllerGetAllInputEventsRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Get all visit events
     */
    async analyticsControllerGetAllVisitEventsRaw(requestParameters: AnalyticsControllerGetAllVisitEventsRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<GetAllVisitEventsResponse>> {
        if (requestParameters['projectName'] == null) {
            throw new runtime.RequiredError(
                'projectName',
                'Required parameter "projectName" was null or undefined when calling analyticsControllerGetAllVisitEvents().'
            );
        }

        const queryParameters: any = {};

        if (requestParameters['projectName'] != null) {
            queryParameters['projectName'] = requestParameters['projectName'];
        }

        if (requestParameters['afterTime'] != null) {
            queryParameters['afterTime'] = requestParameters['afterTime'];
        }

        if (requestParameters['limit'] != null) {
            queryParameters['limit'] = requestParameters['limit'];
        }

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("API_Key", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }
        const response = await this.request({
            path: `/analytics/events/visit/all`,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => GetAllVisitEventsResponseFromJSON(jsonValue));
    }

    /**
     * Get all visit events
     */
    async analyticsControllerGetAllVisitEvents(requestParameters: AnalyticsControllerGetAllVisitEventsRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<GetAllVisitEventsResponse> {
        const response = await this.analyticsControllerGetAllVisitEventsRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Get click events with pagination
     */
    async analyticsControllerGetClickEventsPaginatedRaw(requestParameters: AnalyticsControllerGetClickEventsPaginatedRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<GetClickEventsResponse>> {
        if (requestParameters['projectName'] == null) {
            throw new runtime.RequiredError(
                'projectName',
                'Required parameter "projectName" was null or undefined when calling analyticsControllerGetClickEventsPaginated().'
            );
        }

        const queryParameters: any = {};

        if (requestParameters['projectName'] != null) {
            queryParameters['projectName'] = requestParameters['projectName'];
        }

        if (requestParameters['afterId'] != null) {
            queryParameters['afterId'] = requestParameters['afterId'];
        }

        if (requestParameters['environment'] != null) {
            queryParameters['environment'] = requestParameters['environment'];
        }

        if (requestParameters['limit'] != null) {
            queryParameters['limit'] = requestParameters['limit'];
        }

        if (requestParameters['afterTime'] != null) {
            queryParameters['afterTime'] = requestParameters['afterTime'];
        }

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("API_Key", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }
        const response = await this.request({
            path: `/analytics/events/click`,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => GetClickEventsResponseFromJSON(jsonValue));
    }

    /**
     * Get click events with pagination
     */
    async analyticsControllerGetClickEventsPaginated(requestParameters: AnalyticsControllerGetClickEventsPaginatedRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<GetClickEventsResponse> {
        const response = await this.analyticsControllerGetClickEventsPaginatedRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Get custom event types for a project
     */
    async analyticsControllerGetCustomEventTypesRaw(requestParameters: AnalyticsControllerGetCustomEventTypesRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<GetAllCustomEventTypeResponse>> {
        if (requestParameters['projectName'] == null) {
            throw new runtime.RequiredError(
                'projectName',
                'Required parameter "projectName" was null or undefined when calling analyticsControllerGetCustomEventTypes().'
            );
        }

        const queryParameters: any = {};

        if (requestParameters['projectName'] != null) {
            queryParameters['projectName'] = requestParameters['projectName'];
        }

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("API_Key", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }
        const response = await this.request({
            path: `/analytics/custom-event-types`,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => GetAllCustomEventTypeResponseFromJSON(jsonValue));
    }

    /**
     * Get custom event types for a project
     */
    async analyticsControllerGetCustomEventTypes(requestParameters: AnalyticsControllerGetCustomEventTypesRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<GetAllCustomEventTypeResponse> {
        const response = await this.analyticsControllerGetCustomEventTypesRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Get custom events with pagination
     */
    async analyticsControllerGetCustomEventsPaginatedRaw(requestParameters: AnalyticsControllerGetCustomEventsPaginatedRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<GetCustomEventsResponse>> {
        if (requestParameters['projectName'] == null) {
            throw new runtime.RequiredError(
                'projectName',
                'Required parameter "projectName" was null or undefined when calling analyticsControllerGetCustomEventsPaginated().'
            );
        }

        if (requestParameters['category'] == null) {
            throw new runtime.RequiredError(
                'category',
                'Required parameter "category" was null or undefined when calling analyticsControllerGetCustomEventsPaginated().'
            );
        }

        if (requestParameters['subcategory'] == null) {
            throw new runtime.RequiredError(
                'subcategory',
                'Required parameter "subcategory" was null or undefined when calling analyticsControllerGetCustomEventsPaginated().'
            );
        }

        const queryParameters: any = {};

        if (requestParameters['projectName'] != null) {
            queryParameters['projectName'] = requestParameters['projectName'];
        }

        if (requestParameters['afterId'] != null) {
            queryParameters['afterId'] = requestParameters['afterId'];
        }

        if (requestParameters['environment'] != null) {
            queryParameters['environment'] = requestParameters['environment'];
        }

        if (requestParameters['limit'] != null) {
            queryParameters['limit'] = requestParameters['limit'];
        }

        if (requestParameters['afterTime'] != null) {
            queryParameters['afterTime'] = requestParameters['afterTime'];
        }

        if (requestParameters['category'] != null) {
            queryParameters['category'] = requestParameters['category'];
        }

        if (requestParameters['subcategory'] != null) {
            queryParameters['subcategory'] = requestParameters['subcategory'];
        }

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("API_Key", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }
        const response = await this.request({
            path: `/analytics/events/custom`,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => GetCustomEventsResponseFromJSON(jsonValue));
    }

    /**
     * Get custom events with pagination
     */
    async analyticsControllerGetCustomEventsPaginated(requestParameters: AnalyticsControllerGetCustomEventsPaginatedRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<GetCustomEventsResponse> {
        const response = await this.analyticsControllerGetCustomEventsPaginatedRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Get custom graph types by event type ID
     */
    async analyticsControllerGetCustomGraphTypesByIdRaw(requestParameters: AnalyticsControllerGetCustomGraphTypesByIdRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<CustomGraphTypeResponse>> {
        if (requestParameters['projectName'] == null) {
            throw new runtime.RequiredError(
                'projectName',
                'Required parameter "projectName" was null or undefined when calling analyticsControllerGetCustomGraphTypesById().'
            );
        }

        if (requestParameters['eventTypeId'] == null) {
            throw new runtime.RequiredError(
                'eventTypeId',
                'Required parameter "eventTypeId" was null or undefined when calling analyticsControllerGetCustomGraphTypesById().'
            );
        }

        const queryParameters: any = {};

        if (requestParameters['projectName'] != null) {
            queryParameters['projectName'] = requestParameters['projectName'];
        }

        if (requestParameters['eventTypeId'] != null) {
            queryParameters['eventTypeId'] = requestParameters['eventTypeId'];
        }

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("API_Key", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }
        const response = await this.request({
            path: `/analytics/custom-graph-types`,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => CustomGraphTypeResponseFromJSON(jsonValue));
    }

    /**
     * Get custom graph types by event type ID
     */
    async analyticsControllerGetCustomGraphTypesById(requestParameters: AnalyticsControllerGetCustomGraphTypesByIdRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<CustomGraphTypeResponse> {
        const response = await this.analyticsControllerGetCustomGraphTypesByIdRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Get input events with pagination
     */
    async analyticsControllerGetInputEventsPaginatedRaw(requestParameters: AnalyticsControllerGetInputEventsPaginatedRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<GetInputEventsResponse>> {
        if (requestParameters['projectName'] == null) {
            throw new runtime.RequiredError(
                'projectName',
                'Required parameter "projectName" was null or undefined when calling analyticsControllerGetInputEventsPaginated().'
            );
        }

        const queryParameters: any = {};

        if (requestParameters['projectName'] != null) {
            queryParameters['projectName'] = requestParameters['projectName'];
        }

        if (requestParameters['afterId'] != null) {
            queryParameters['afterId'] = requestParameters['afterId'];
        }

        if (requestParameters['environment'] != null) {
            queryParameters['environment'] = requestParameters['environment'];
        }

        if (requestParameters['limit'] != null) {
            queryParameters['limit'] = requestParameters['limit'];
        }

        if (requestParameters['afterTime'] != null) {
            queryParameters['afterTime'] = requestParameters['afterTime'];
        }

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("API_Key", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }
        const response = await this.request({
            path: `/analytics/events/input`,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => GetInputEventsResponseFromJSON(jsonValue));
    }

    /**
     * Get input events with pagination
     */
    async analyticsControllerGetInputEventsPaginated(requestParameters: AnalyticsControllerGetInputEventsPaginatedRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<GetInputEventsResponse> {
        const response = await this.analyticsControllerGetInputEventsPaginatedRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Get visit events with pagination
     */
    async analyticsControllerGetVisitEventsPaginatedRaw(requestParameters: AnalyticsControllerGetVisitEventsPaginatedRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<GetVisitEventsResponse>> {
        if (requestParameters['projectName'] == null) {
            throw new runtime.RequiredError(
                'projectName',
                'Required parameter "projectName" was null or undefined when calling analyticsControllerGetVisitEventsPaginated().'
            );
        }

        const queryParameters: any = {};

        if (requestParameters['projectName'] != null) {
            queryParameters['projectName'] = requestParameters['projectName'];
        }

        if (requestParameters['afterId'] != null) {
            queryParameters['afterId'] = requestParameters['afterId'];
        }

        if (requestParameters['environment'] != null) {
            queryParameters['environment'] = requestParameters['environment'];
        }

        if (requestParameters['limit'] != null) {
            queryParameters['limit'] = requestParameters['limit'];
        }

        if (requestParameters['afterTime'] != null) {
            queryParameters['afterTime'] = requestParameters['afterTime'];
        }

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("API_Key", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }
        const response = await this.request({
            path: `/analytics/events/visit`,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => GetVisitEventsResponseFromJSON(jsonValue));
    }

    /**
     * Get visit events with pagination
     */
    async analyticsControllerGetVisitEventsPaginated(requestParameters: AnalyticsControllerGetVisitEventsPaginatedRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<GetVisitEventsResponse> {
        const response = await this.analyticsControllerGetVisitEventsPaginatedRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Log a click event
     */
    async analyticsControllerLogClickEventRaw(requestParameters: AnalyticsControllerLogClickEventRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<ClickEventResponse>> {
        if (requestParameters['logClickEventRequest'] == null) {
            throw new runtime.RequiredError(
                'logClickEventRequest',
                'Required parameter "logClickEventRequest" was null or undefined when calling analyticsControllerLogClickEvent().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("API_Key", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }
        const response = await this.request({
            path: `/analytics/events/click`,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: LogClickEventRequestToJSON(requestParameters['logClickEventRequest']),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => ClickEventResponseFromJSON(jsonValue));
    }

    /**
     * Log a click event
     */
    async analyticsControllerLogClickEvent(requestParameters: AnalyticsControllerLogClickEventRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<ClickEventResponse> {
        const response = await this.analyticsControllerLogClickEventRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Log a custom event
     */
    async analyticsControllerLogCustomEventRaw(requestParameters: AnalyticsControllerLogCustomEventRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<CustomEventResponse>> {
        if (requestParameters['logCustomEventRequest'] == null) {
            throw new runtime.RequiredError(
                'logCustomEventRequest',
                'Required parameter "logCustomEventRequest" was null or undefined when calling analyticsControllerLogCustomEvent().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("API_Key", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }
        const response = await this.request({
            path: `/analytics/events/custom`,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: LogCustomEventRequestToJSON(requestParameters['logCustomEventRequest']),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => CustomEventResponseFromJSON(jsonValue));
    }

    /**
     * Log a custom event
     */
    async analyticsControllerLogCustomEvent(requestParameters: AnalyticsControllerLogCustomEventRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<CustomEventResponse> {
        const response = await this.analyticsControllerLogCustomEventRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Log an input event
     */
    async analyticsControllerLogInputEventRaw(requestParameters: AnalyticsControllerLogInputEventRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<InputEventResponse>> {
        if (requestParameters['logInputEventRequest'] == null) {
            throw new runtime.RequiredError(
                'logInputEventRequest',
                'Required parameter "logInputEventRequest" was null or undefined when calling analyticsControllerLogInputEvent().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("API_Key", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }
        const response = await this.request({
            path: `/analytics/events/input`,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: LogInputEventRequestToJSON(requestParameters['logInputEventRequest']),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => InputEventResponseFromJSON(jsonValue));
    }

    /**
     * Log an input event
     */
    async analyticsControllerLogInputEvent(requestParameters: AnalyticsControllerLogInputEventRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<InputEventResponse> {
        const response = await this.analyticsControllerLogInputEventRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Log a visit event
     */
    async analyticsControllerLogVisitEventRaw(requestParameters: AnalyticsControllerLogVisitEventRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<VisitEventResponse>> {
        if (requestParameters['logVisitEventRequest'] == null) {
            throw new runtime.RequiredError(
                'logVisitEventRequest',
                'Required parameter "logVisitEventRequest" was null or undefined when calling analyticsControllerLogVisitEvent().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("API_Key", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }
        const response = await this.request({
            path: `/analytics/events/visit`,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: LogVisitEventRequestToJSON(requestParameters['logVisitEventRequest']),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => VisitEventResponseFromJSON(jsonValue));
    }

    /**
     * Log a visit event
     */
    async analyticsControllerLogVisitEvent(requestParameters: AnalyticsControllerLogVisitEventRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<VisitEventResponse> {
        const response = await this.analyticsControllerLogVisitEventRaw(requestParameters, initOverrides);
        return await response.value();
    }

}
