/* tslint:disable */
/* eslint-disable */
/**
 * Juno
 * Juno Public API Docs
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import type {
  IssueApiKeyRequest,
  IssueApiKeyResponse,
  IssueJWTResponse,
} from '../models/index';
import {
    IssueApiKeyRequestFromJSON,
    IssueApiKeyRequestToJSON,
    IssueApiKeyResponseFromJSON,
    IssueApiKeyResponseToJSON,
    IssueJWTResponseFromJSON,
    IssueJWTResponseToJSON,
} from '../models/index';

export interface AuthControllerCreateApiKeyRequest {
    xUserPassword: string;
    xUserEmail: string;
    issueApiKeyRequest: IssueApiKeyRequest;
}

export interface AuthControllerDeleteApiKeyRequest {
    authorization: string;
}

export interface AuthControllerGetApiKeyJWTRequest {
    authorization: string;
}

export interface AuthControllerGetUserJWTRequest {
    xUserPassword: string;
    xUserEmail: string;
}

export interface AuthControllerTestAuthRequest {
    authorization: string;
}

/**
 * 
 */
export class AuthApi extends runtime.BaseAPI {

    /**
     * Issues a new API key for the project tied to the specified environment.
     */
    async authControllerCreateApiKeyRaw(requestParameters: AuthControllerCreateApiKeyRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<IssueApiKeyResponse>> {
        if (requestParameters['xUserPassword'] == null) {
            throw new runtime.RequiredError(
                'xUserPassword',
                'Required parameter "xUserPassword" was null or undefined when calling authControllerCreateApiKey().'
            );
        }

        if (requestParameters['xUserEmail'] == null) {
            throw new runtime.RequiredError(
                'xUserEmail',
                'Required parameter "xUserEmail" was null or undefined when calling authControllerCreateApiKey().'
            );
        }

        if (requestParameters['issueApiKeyRequest'] == null) {
            throw new runtime.RequiredError(
                'issueApiKeyRequest',
                'Required parameter "issueApiKeyRequest" was null or undefined when calling authControllerCreateApiKey().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (requestParameters['xUserPassword'] != null) {
            headerParameters['X-User-Password'] = String(requestParameters['xUserPassword']);
        }

        if (requestParameters['xUserEmail'] != null) {
            headerParameters['X-User-Email'] = String(requestParameters['xUserEmail']);
        }

        const response = await this.request({
            path: `/auth/key`,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: IssueApiKeyRequestToJSON(requestParameters['issueApiKeyRequest']),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => IssueApiKeyResponseFromJSON(jsonValue));
    }

    /**
     * Issues a new API key for the project tied to the specified environment.
     */
    async authControllerCreateApiKey(requestParameters: AuthControllerCreateApiKeyRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<IssueApiKeyResponse> {
        const response = await this.authControllerCreateApiKeyRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Deletes an API key, detaching it from its project.
     */
    async authControllerDeleteApiKeyRaw(requestParameters: AuthControllerDeleteApiKeyRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<void>> {
        if (requestParameters['authorization'] == null) {
            throw new runtime.RequiredError(
                'authorization',
                'Required parameter "authorization" was null or undefined when calling authControllerDeleteApiKey().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (requestParameters['authorization'] != null) {
            headerParameters['Authorization'] = String(requestParameters['authorization']);
        }

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("API_Key", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }
        const response = await this.request({
            path: `/auth/key`,
            method: 'DELETE',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.VoidApiResponse(response);
    }

    /**
     * Deletes an API key, detaching it from its project.
     */
    async authControllerDeleteApiKey(requestParameters: AuthControllerDeleteApiKeyRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<void> {
        await this.authControllerDeleteApiKeyRaw(requestParameters, initOverrides);
    }

    /**
     * JSON Web Tokens are used for the vast majority of API-gateway calls. The Juno SDK provides the means of automatically authenticating through this route given a valid API key.
     * Generates a temporary JWT for the project tied to a specified API key.
     */
    async authControllerGetApiKeyJWTRaw(requestParameters: AuthControllerGetApiKeyJWTRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<IssueJWTResponse>> {
        if (requestParameters['authorization'] == null) {
            throw new runtime.RequiredError(
                'authorization',
                'Required parameter "authorization" was null or undefined when calling authControllerGetApiKeyJWT().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (requestParameters['authorization'] != null) {
            headerParameters['Authorization'] = String(requestParameters['authorization']);
        }

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("API_Key", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }
        const response = await this.request({
            path: `/auth/api_key/jwt`,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => IssueJWTResponseFromJSON(jsonValue));
    }

    /**
     * JSON Web Tokens are used for the vast majority of API-gateway calls. The Juno SDK provides the means of automatically authenticating through this route given a valid API key.
     * Generates a temporary JWT for the project tied to a specified API key.
     */
    async authControllerGetApiKeyJWT(requestParameters: AuthControllerGetApiKeyJWTRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<IssueJWTResponse> {
        const response = await this.authControllerGetApiKeyJWTRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * JSON Web Tokens are used for the vast majority of API-gateway calls. The Juno SDK provides the means of automatically authenticating through this route given valid user credentials.
     * Generates a temporary JWT tied to a specified user.
     */
    async authControllerGetUserJWTRaw(requestParameters: AuthControllerGetUserJWTRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<IssueJWTResponse>> {
        if (requestParameters['xUserPassword'] == null) {
            throw new runtime.RequiredError(
                'xUserPassword',
                'Required parameter "xUserPassword" was null or undefined when calling authControllerGetUserJWT().'
            );
        }

        if (requestParameters['xUserEmail'] == null) {
            throw new runtime.RequiredError(
                'xUserEmail',
                'Required parameter "xUserEmail" was null or undefined when calling authControllerGetUserJWT().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (requestParameters['xUserPassword'] != null) {
            headerParameters['X-User-Password'] = String(requestParameters['xUserPassword']);
        }

        if (requestParameters['xUserEmail'] != null) {
            headerParameters['X-User-Email'] = String(requestParameters['xUserEmail']);
        }

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("API_Key", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }
        const response = await this.request({
            path: `/auth/user/jwt`,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => IssueJWTResponseFromJSON(jsonValue));
    }

    /**
     * JSON Web Tokens are used for the vast majority of API-gateway calls. The Juno SDK provides the means of automatically authenticating through this route given valid user credentials.
     * Generates a temporary JWT tied to a specified user.
     */
    async authControllerGetUserJWT(requestParameters: AuthControllerGetUserJWTRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<IssueJWTResponse> {
        const response = await this.authControllerGetUserJWTRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * This endpoint validates a user JWT token and returns the associated user information if valid
     * Validates user JWT and returns user data
     */
    async authControllerTestAuthRaw(requestParameters: AuthControllerTestAuthRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<void>> {
        if (requestParameters['authorization'] == null) {
            throw new runtime.RequiredError(
                'authorization',
                'Required parameter "authorization" was null or undefined when calling authControllerTestAuth().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (requestParameters['authorization'] != null) {
            headerParameters['Authorization'] = String(requestParameters['authorization']);
        }

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("API_Key", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }
        const response = await this.request({
            path: `/auth/test-auth`,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.VoidApiResponse(response);
    }

    /**
     * This endpoint validates a user JWT token and returns the associated user information if valid
     * Validates user JWT and returns user data
     */
    async authControllerTestAuth(requestParameters: AuthControllerTestAuthRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<void> {
        await this.authControllerTestAuthRaw(requestParameters, initOverrides);
    }

}
