/* tslint:disable */
/* eslint-disable */
/**
 * Juno
 * Juno Public API Docs
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import type {
  AggregateInterval,
  EmailConfigResponse,
  RegisterDomainModel,
  RegisterDomainResponse,
  RegisterEmailModel,
  RegisterEmailResponse,
  SendEmailModel,
  SendEmailResponse,
  SendEmailStatisticsResponses,
  SetupEmailResponse,
  SetupEmailServiceModel,
  VerifyDomainModel,
} from '../models/index';
import {
    AggregateIntervalFromJSON,
    AggregateIntervalToJSON,
    EmailConfigResponseFromJSON,
    EmailConfigResponseToJSON,
    RegisterDomainModelFromJSON,
    RegisterDomainModelToJSON,
    RegisterDomainResponseFromJSON,
    RegisterDomainResponseToJSON,
    RegisterEmailModelFromJSON,
    RegisterEmailModelToJSON,
    RegisterEmailResponseFromJSON,
    RegisterEmailResponseToJSON,
    SendEmailModelFromJSON,
    SendEmailModelToJSON,
    SendEmailResponseFromJSON,
    SendEmailResponseToJSON,
    SendEmailStatisticsResponsesFromJSON,
    SendEmailStatisticsResponsesToJSON,
    SetupEmailResponseFromJSON,
    SetupEmailResponseToJSON,
    SetupEmailServiceModelFromJSON,
    SetupEmailServiceModelToJSON,
    VerifyDomainModelFromJSON,
    VerifyDomainModelToJSON,
} from '../models/index';

export interface EmailControllerGetEmailConfigByIdRequest {
    id: string;
}

export interface EmailControllerGetStatisticsRequest {
    startDate: string;
    limit?: number;
    offset?: number;
    aggregatedBy?: AggregateInterval;
    endDate?: string;
}

export interface EmailControllerRegisterEmailDomainRequest {
    registerDomainModel: RegisterDomainModel;
}

export interface EmailControllerRegisterSenderAddressRequest {
    registerEmailModel: RegisterEmailModel;
}

export interface EmailControllerSendEmailRequest {
    sendEmailModel: SendEmailModel;
}

export interface EmailControllerSetupRequest {
    setupEmailServiceModel: SetupEmailServiceModel;
}

export interface EmailControllerVerifySenderDomainRequest {
    verifyDomainModel: VerifyDomainModel;
}

/**
 * 
 */
export class EmailApi extends runtime.BaseAPI {

    /**
     * Get email configuration by ID
     */
    async emailControllerGetEmailConfigByIdRaw(requestParameters: EmailControllerGetEmailConfigByIdRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<EmailConfigResponse>> {
        if (requestParameters['id'] == null) {
            throw new runtime.RequiredError(
                'id',
                'Required parameter "id" was null or undefined when calling emailControllerGetEmailConfigById().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("API_Key", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }
        const response = await this.request({
            path: `/email/config/{id}`.replace(`{${"id"}}`, encodeURIComponent(String(requestParameters['id']))),
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => EmailConfigResponseFromJSON(jsonValue));
    }

    /**
     * Get email configuration by ID
     */
    async emailControllerGetEmailConfigById(requestParameters: EmailControllerGetEmailConfigByIdRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<EmailConfigResponse> {
        const response = await this.emailControllerGetEmailConfigByIdRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Gets overall email analytics
     */
    async emailControllerGetStatisticsRaw(requestParameters: EmailControllerGetStatisticsRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<SendEmailStatisticsResponses>> {
        if (requestParameters['startDate'] == null) {
            throw new runtime.RequiredError(
                'startDate',
                'Required parameter "startDate" was null or undefined when calling emailControllerGetStatistics().'
            );
        }

        const queryParameters: any = {};

        if (requestParameters['startDate'] != null) {
            queryParameters['startDate'] = requestParameters['startDate'];
        }

        if (requestParameters['limit'] != null) {
            queryParameters['limit'] = requestParameters['limit'];
        }

        if (requestParameters['offset'] != null) {
            queryParameters['offset'] = requestParameters['offset'];
        }

        if (requestParameters['aggregatedBy'] != null) {
            queryParameters['aggregatedBy'] = requestParameters['aggregatedBy'];
        }

        if (requestParameters['endDate'] != null) {
            queryParameters['endDate'] = requestParameters['endDate'];
        }

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("API_Key", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }
        const response = await this.request({
            path: `/email/analytics`,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => SendEmailStatisticsResponsesFromJSON(jsonValue));
    }

    /**
     * Gets overall email analytics
     */
    async emailControllerGetStatistics(requestParameters: EmailControllerGetStatisticsRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<SendEmailStatisticsResponses> {
        const response = await this.emailControllerGetStatisticsRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Registers a sender domain with SendGrid.
     */
    async emailControllerRegisterEmailDomainRaw(requestParameters: EmailControllerRegisterEmailDomainRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<RegisterDomainResponse>> {
        if (requestParameters['registerDomainModel'] == null) {
            throw new runtime.RequiredError(
                'registerDomainModel',
                'Required parameter "registerDomainModel" was null or undefined when calling emailControllerRegisterEmailDomain().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("API_Key", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }
        const response = await this.request({
            path: `/email/register-domain`,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: RegisterDomainModelToJSON(requestParameters['registerDomainModel']),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => RegisterDomainResponseFromJSON(jsonValue));
    }

    /**
     * Registers a sender domain with SendGrid.
     */
    async emailControllerRegisterEmailDomain(requestParameters: EmailControllerRegisterEmailDomainRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<RegisterDomainResponse> {
        const response = await this.emailControllerRegisterEmailDomainRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Registers a sender email address.
     */
    async emailControllerRegisterSenderAddressRaw(requestParameters: EmailControllerRegisterSenderAddressRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<RegisterEmailResponse>> {
        if (requestParameters['registerEmailModel'] == null) {
            throw new runtime.RequiredError(
                'registerEmailModel',
                'Required parameter "registerEmailModel" was null or undefined when calling emailControllerRegisterSenderAddress().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("API_Key", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }
        const response = await this.request({
            path: `/email/register-sender`,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: RegisterEmailModelToJSON(requestParameters['registerEmailModel']),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => RegisterEmailResponseFromJSON(jsonValue));
    }

    /**
     * Registers a sender email address.
     */
    async emailControllerRegisterSenderAddress(requestParameters: EmailControllerRegisterSenderAddressRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<RegisterEmailResponse> {
        const response = await this.emailControllerRegisterSenderAddressRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Sends an email using Juno services.
     */
    async emailControllerSendEmailRaw(requestParameters: EmailControllerSendEmailRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<SendEmailResponse>> {
        if (requestParameters['sendEmailModel'] == null) {
            throw new runtime.RequiredError(
                'sendEmailModel',
                'Required parameter "sendEmailModel" was null or undefined when calling emailControllerSendEmail().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("API_Key", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }
        const response = await this.request({
            path: `/email/send`,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: SendEmailModelToJSON(requestParameters['sendEmailModel']),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => SendEmailResponseFromJSON(jsonValue));
    }

    /**
     * Sends an email using Juno services.
     */
    async emailControllerSendEmail(requestParameters: EmailControllerSendEmailRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<SendEmailResponse> {
        const response = await this.emailControllerSendEmailRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Sets up an email service with the given Sendgrid API Key
     */
    async emailControllerSetupRaw(requestParameters: EmailControllerSetupRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<SetupEmailResponse>> {
        if (requestParameters['setupEmailServiceModel'] == null) {
            throw new runtime.RequiredError(
                'setupEmailServiceModel',
                'Required parameter "setupEmailServiceModel" was null or undefined when calling emailControllerSetup().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("API_Key", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }
        const response = await this.request({
            path: `/email/setup`,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: SetupEmailServiceModelToJSON(requestParameters['setupEmailServiceModel']),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => SetupEmailResponseFromJSON(jsonValue));
    }

    /**
     * Sets up an email service with the given Sendgrid API Key
     */
    async emailControllerSetup(requestParameters: EmailControllerSetupRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<SetupEmailResponse> {
        const response = await this.emailControllerSetupRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Verifies a sender domain registration status.
     */
    async emailControllerVerifySenderDomainRaw(requestParameters: EmailControllerVerifySenderDomainRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<RegisterDomainResponse>> {
        if (requestParameters['verifyDomainModel'] == null) {
            throw new runtime.RequiredError(
                'verifyDomainModel',
                'Required parameter "verifyDomainModel" was null or undefined when calling emailControllerVerifySenderDomain().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("API_Key", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }
        const response = await this.request({
            path: `/email/verify-domain`,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: VerifyDomainModelToJSON(requestParameters['verifyDomainModel']),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => RegisterDomainResponseFromJSON(jsonValue));
    }

    /**
     * Verifies a sender domain registration status.
     */
    async emailControllerVerifySenderDomain(requestParameters: EmailControllerVerifySenderDomainRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<RegisterDomainResponse> {
        const response = await this.emailControllerVerifySenderDomainRaw(requestParameters, initOverrides);
        return await response.value();
    }

}
