/* tslint:disable */
/* eslint-disable */
/**
 * Juno
 * Juno Public API Docs
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import type {
  FileConfigResponse,
  SetupFileServiceResponse,
} from '../models/index';
import {
    FileConfigResponseFromJSON,
    FileConfigResponseToJSON,
    SetupFileServiceResponseFromJSON,
    SetupFileServiceResponseToJSON,
} from '../models/index';

export interface FileConfigControllerDeleteFileConfigByProjectIdRequest {
    projectId: string;
}

export interface FileConfigControllerGetFileConfigByProjectIdRequest {
    projectId: string;
}

/**
 * 
 */
export class FileConfigApi extends runtime.BaseAPI {

    /**
     * Delete file configuration by project ID
     */
    async fileConfigControllerDeleteFileConfigByProjectIdRaw(requestParameters: FileConfigControllerDeleteFileConfigByProjectIdRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<FileConfigResponse>> {
        if (requestParameters['projectId'] == null) {
            throw new runtime.RequiredError(
                'projectId',
                'Required parameter "projectId" was null or undefined when calling fileConfigControllerDeleteFileConfigByProjectId().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("API_Key", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }
        const response = await this.request({
            path: `/file/config/delete/{projectId}`.replace(`{${"projectId"}}`, encodeURIComponent(String(requestParameters['projectId']))),
            method: 'DELETE',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => FileConfigResponseFromJSON(jsonValue));
    }

    /**
     * Delete file configuration by project ID
     */
    async fileConfigControllerDeleteFileConfigByProjectId(requestParameters: FileConfigControllerDeleteFileConfigByProjectIdRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<FileConfigResponse> {
        const response = await this.fileConfigControllerDeleteFileConfigByProjectIdRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Get file configuration by project ID
     */
    async fileConfigControllerGetFileConfigByProjectIdRaw(requestParameters: FileConfigControllerGetFileConfigByProjectIdRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<FileConfigResponse>> {
        if (requestParameters['projectId'] == null) {
            throw new runtime.RequiredError(
                'projectId',
                'Required parameter "projectId" was null or undefined when calling fileConfigControllerGetFileConfigByProjectId().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("API_Key", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }
        const response = await this.request({
            path: `/file/config/{projectId}`.replace(`{${"projectId"}}`, encodeURIComponent(String(requestParameters['projectId']))),
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => FileConfigResponseFromJSON(jsonValue));
    }

    /**
     * Get file configuration by project ID
     */
    async fileConfigControllerGetFileConfigByProjectId(requestParameters: FileConfigControllerGetFileConfigByProjectIdRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<FileConfigResponse> {
        const response = await this.fileConfigControllerGetFileConfigByProjectIdRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Sets up file services for the Project/Environment
     */
    async fileConfigControllerSetupRaw(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<SetupFileServiceResponse>> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("API_Key", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }
        const response = await this.request({
            path: `/file/config/setup`,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => SetupFileServiceResponseFromJSON(jsonValue));
    }

    /**
     * Sets up file services for the Project/Environment
     */
    async fileConfigControllerSetup(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<SetupFileServiceResponse> {
        const response = await this.fileConfigControllerSetupRaw(initOverrides);
        return await response.value();
    }

}
