/* tslint:disable */
/* eslint-disable */
/**
 * Juno
 * Juno Public API Docs
 *
 * The version of the OpenAPI document: 1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import * as runtime from '../runtime';
import type { DeleteFilesModel, DeleteFilesResponse } from '../models/index';
import {
  DeleteFilesModelFromJSON,
  DeleteFilesModelToJSON,
  DeleteFilesResponseFromJSON,
  DeleteFilesResponseToJSON,
} from '../models/index';

export interface FileDeleteControllerDeleteFilesRequest {
  deleteFilesModel: DeleteFilesModel;
}

/**
 *
 */
export class FileDeleteApi extends runtime.BaseAPI {
  /**
   * Delete files from a bucket
   */
  async fileDeleteControllerDeleteFilesRaw(
    requestParameters: FileDeleteControllerDeleteFilesRequest,
    initOverrides?: RequestInit | runtime.InitOverrideFunction
  ): Promise<runtime.ApiResponse<DeleteFilesResponse>> {
    if (requestParameters['deleteFilesModel'] == null) {
      throw new runtime.RequiredError(
        'deleteFilesModel',
        'Required parameter "deleteFilesModel" was null or undefined when calling fileDeleteControllerDeleteFiles().'
      );
    }

    const queryParameters: any = {};

    const headerParameters: runtime.HTTPHeaders = {};

    headerParameters['Content-Type'] = 'application/json';

    if (this.configuration && this.configuration.accessToken) {
      const token = this.configuration.accessToken;
      const tokenString = await token('API_Key', []);

      if (tokenString) {
        headerParameters['Authorization'] = `Bearer ${tokenString}`;
      }
    }
    const response = await this.request(
      {
        path: `/file/delete`,
        method: 'DELETE',
        headers: headerParameters,
        query: queryParameters,
        body: DeleteFilesModelToJSON(requestParameters['deleteFilesModel']),
      },
      initOverrides
    );

    return new runtime.JSONApiResponse(response, (jsonValue) =>
      DeleteFilesResponseFromJSON(jsonValue)
    );
  }

  /**
   * Delete files from a bucket
   */
  async fileDeleteControllerDeleteFiles(
    requestParameters: FileDeleteControllerDeleteFilesRequest,
    initOverrides?: RequestInit | runtime.InitOverrideFunction
  ): Promise<DeleteFilesResponse> {
    const response = await this.fileDeleteControllerDeleteFilesRaw(
      requestParameters,
      initOverrides
    );
    return await response.value();
  }
}
