/* tslint:disable */
/* eslint-disable */
/**
 * Juno
 * Juno Public API Docs
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import type {
  DownloadFileModel,
  DownloadFileResponse,
} from '../models/index';
import {
    DownloadFileModelFromJSON,
    DownloadFileModelToJSON,
    DownloadFileResponseFromJSON,
    DownloadFileResponseToJSON,
} from '../models/index';

export interface FileDownloadControllerDownloadFileRequest {
    downloadFileModel: DownloadFileModel;
}

/**
 * 
 */
export class FileDownloadApi extends runtime.BaseAPI {

    /**
     * Downloads a file
     */
    async fileDownloadControllerDownloadFileRaw(requestParameters: FileDownloadControllerDownloadFileRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<DownloadFileResponse>> {
        if (requestParameters['downloadFileModel'] == null) {
            throw new runtime.RequiredError(
                'downloadFileModel',
                'Required parameter "downloadFileModel" was null or undefined when calling fileDownloadControllerDownloadFile().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("API_Key", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }
        const response = await this.request({
            path: `/file/download`,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: DownloadFileModelToJSON(requestParameters['downloadFileModel']),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => DownloadFileResponseFromJSON(jsonValue));
    }

    /**
     * Downloads a file
     */
    async fileDownloadControllerDownloadFile(requestParameters: FileDownloadControllerDownloadFileRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<DownloadFileResponse> {
        const response = await this.fileDownloadControllerDownloadFileRaw(requestParameters, initOverrides);
        return await response.value();
    }

}
