/* tslint:disable */
/* eslint-disable */
/**
 * Juno
 * Juno Public API Docs
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import type {
  FileProvider,
  FileProviderPartial,
  RegisterFileProviderModel,
} from '../models/index';
import {
    FileProviderFromJSON,
    FileProviderToJSON,
    FileProviderPartialFromJSON,
    FileProviderPartialToJSON,
    RegisterFileProviderModelFromJSON,
    RegisterFileProviderModelToJSON,
} from '../models/index';

export interface FileProviderControllerDeleteFileProviderRequest {
    name: string;
}

export interface FileProviderControllerRegisterFileProviderRequest {
    registerFileProviderModel: RegisterFileProviderModel;
}

/**
 * 
 */
export class FileProviderApi extends runtime.BaseAPI {

    /**
     * Delete File Provider.
     */
    async fileProviderControllerDeleteFileProviderRaw(requestParameters: FileProviderControllerDeleteFileProviderRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<FileProviderPartial>> {
        if (requestParameters['name'] == null) {
            throw new runtime.RequiredError(
                'name',
                'Required parameter "name" was null or undefined when calling fileProviderControllerDeleteFileProvider().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("API_Key", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }
        const response = await this.request({
            path: `/file/provider/{name}`.replace(`{${"name"}}`, encodeURIComponent(String(requestParameters['name']))),
            method: 'DELETE',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => FileProviderPartialFromJSON(jsonValue));
    }

    /**
     * Delete File Provider.
     */
    async fileProviderControllerDeleteFileProvider(requestParameters: FileProviderControllerDeleteFileProviderRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<FileProviderPartial> {
        const response = await this.fileProviderControllerDeleteFileProviderRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Get All File Providers.
     */
    async fileProviderControllerGetAllFileProvidersRaw(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Array<FileProvider>>> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("API_Key", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }
        const response = await this.request({
            path: `/file/provider/all`,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => jsonValue.map(FileProviderFromJSON));
    }

    /**
     * Get All File Providers.
     */
    async fileProviderControllerGetAllFileProviders(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Array<FileProvider>> {
        const response = await this.fileProviderControllerGetAllFileProvidersRaw(initOverrides);
        return await response.value();
    }

    /**
     * Registers a File Provider.
     */
    async fileProviderControllerRegisterFileProviderRaw(requestParameters: FileProviderControllerRegisterFileProviderRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<FileProviderPartial>> {
        if (requestParameters['registerFileProviderModel'] == null) {
            throw new runtime.RequiredError(
                'registerFileProviderModel',
                'Required parameter "registerFileProviderModel" was null or undefined when calling fileProviderControllerRegisterFileProvider().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("API_Key", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }
        const response = await this.request({
            path: `/file/provider`,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: RegisterFileProviderModelToJSON(requestParameters['registerFileProviderModel']),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => FileProviderPartialFromJSON(jsonValue));
    }

    /**
     * Registers a File Provider.
     */
    async fileProviderControllerRegisterFileProvider(requestParameters: FileProviderControllerRegisterFileProviderRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<FileProviderPartial> {
        const response = await this.fileProviderControllerRegisterFileProviderRaw(requestParameters, initOverrides);
        return await response.value();
    }

}
