/* tslint:disable */
/* eslint-disable */
/**
 * Juno
 * Juno Public API Docs
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import type {
  CreateUserModel,
  LinkProjectModel,
  SetUserTypeModel,
  UnlinkProjectModel,
  UserResponse,
  UserResponses,
} from '../models/index';
import {
    CreateUserModelFromJSON,
    CreateUserModelToJSON,
    LinkProjectModelFromJSON,
    LinkProjectModelToJSON,
    SetUserTypeModelFromJSON,
    SetUserTypeModelToJSON,
    UnlinkProjectModelFromJSON,
    UnlinkProjectModelToJSON,
    UserResponseFromJSON,
    UserResponseToJSON,
    UserResponsesFromJSON,
    UserResponsesToJSON,
} from '../models/index';

export interface UserControllerCreateUserRequest {
    createUserModel: CreateUserModel;
    xUserPassword?: string;
    xUserEmail?: string;
}

export interface UserControllerDeleteUserByIdRequest {
    id: string;
    xUserPassword?: string;
    xUserEmail?: string;
}

export interface UserControllerGetAllUsersRequest {
    xUserPassword?: string;
    xUserEmail?: string;
}

export interface UserControllerGetUserByIdRequest {
    id: string;
}

export interface UserControllerLinkUserWithProjectIdRequest {
    id: string;
    linkProjectModel: LinkProjectModel;
    xUserPassword?: string;
    xUserEmail?: string;
}

export interface UserControllerSetUserTypeRequest {
    setUserTypeModel: SetUserTypeModel;
    xUserPassword?: string;
    xUserEmail?: string;
}

export interface UserControllerUnlinkUserFromProjectRequest {
    id: string;
    unlinkProjectModel: UnlinkProjectModel;
    xUserPassword?: string;
    xUserEmail?: string;
}

/**
 * 
 */
export class UserApi extends runtime.BaseAPI {

    /**
     * Create a new user.
     */
    async userControllerCreateUserRaw(requestParameters: UserControllerCreateUserRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<UserResponse>> {
        if (requestParameters['createUserModel'] == null) {
            throw new runtime.RequiredError(
                'createUserModel',
                'Required parameter "createUserModel" was null or undefined when calling userControllerCreateUser().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (requestParameters['xUserPassword'] != null) {
            headerParameters['X-User-Password'] = String(requestParameters['xUserPassword']);
        }

        if (requestParameters['xUserEmail'] != null) {
            headerParameters['X-User-Email'] = String(requestParameters['xUserEmail']);
        }

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("API_Key", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }
        const response = await this.request({
            path: `/user`,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: CreateUserModelToJSON(requestParameters['createUserModel']),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => UserResponseFromJSON(jsonValue));
    }

    /**
     * Create a new user.
     */
    async userControllerCreateUser(requestParameters: UserControllerCreateUserRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<UserResponse> {
        const response = await this.userControllerCreateUserRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Delete an existing user.
     */
    async userControllerDeleteUserByIdRaw(requestParameters: UserControllerDeleteUserByIdRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<UserResponse>> {
        if (requestParameters['id'] == null) {
            throw new runtime.RequiredError(
                'id',
                'Required parameter "id" was null or undefined when calling userControllerDeleteUserById().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (requestParameters['xUserPassword'] != null) {
            headerParameters['X-User-Password'] = String(requestParameters['xUserPassword']);
        }

        if (requestParameters['xUserEmail'] != null) {
            headerParameters['X-User-Email'] = String(requestParameters['xUserEmail']);
        }

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("API_Key", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }
        const response = await this.request({
            path: `/user/id/{id}`.replace(`{${"id"}}`, encodeURIComponent(String(requestParameters['id']))),
            method: 'DELETE',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => UserResponseFromJSON(jsonValue));
    }

    /**
     * Delete an existing user.
     */
    async userControllerDeleteUserById(requestParameters: UserControllerDeleteUserByIdRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<UserResponse> {
        const response = await this.userControllerDeleteUserByIdRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Retrieves all users.
     */
    async userControllerGetAllUsersRaw(requestParameters: UserControllerGetAllUsersRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<UserResponses>> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (requestParameters['xUserPassword'] != null) {
            headerParameters['X-User-Password'] = String(requestParameters['xUserPassword']);
        }

        if (requestParameters['xUserEmail'] != null) {
            headerParameters['X-User-Email'] = String(requestParameters['xUserEmail']);
        }

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("API_Key", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }
        const response = await this.request({
            path: `/user`,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => UserResponsesFromJSON(jsonValue));
    }

    /**
     * Retrieves all users.
     */
    async userControllerGetAllUsers(requestParameters: UserControllerGetAllUsersRequest = {}, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<UserResponses> {
        const response = await this.userControllerGetAllUsersRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Retrieve an existing user.
     */
    async userControllerGetUserByIdRaw(requestParameters: UserControllerGetUserByIdRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<UserResponse>> {
        if (requestParameters['id'] == null) {
            throw new runtime.RequiredError(
                'id',
                'Required parameter "id" was null or undefined when calling userControllerGetUserById().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("API_Key", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }
        const response = await this.request({
            path: `/user/id/{id}`.replace(`{${"id"}}`, encodeURIComponent(String(requestParameters['id']))),
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => UserResponseFromJSON(jsonValue));
    }

    /**
     * Retrieve an existing user.
     */
    async userControllerGetUserById(requestParameters: UserControllerGetUserByIdRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<UserResponse> {
        const response = await this.userControllerGetUserByIdRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Associates a user with a project ID.
     * Link user to project.
     */
    async userControllerLinkUserWithProjectIdRaw(requestParameters: UserControllerLinkUserWithProjectIdRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<UserResponse>> {
        if (requestParameters['id'] == null) {
            throw new runtime.RequiredError(
                'id',
                'Required parameter "id" was null or undefined when calling userControllerLinkUserWithProjectId().'
            );
        }

        if (requestParameters['linkProjectModel'] == null) {
            throw new runtime.RequiredError(
                'linkProjectModel',
                'Required parameter "linkProjectModel" was null or undefined when calling userControllerLinkUserWithProjectId().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (requestParameters['xUserPassword'] != null) {
            headerParameters['X-User-Password'] = String(requestParameters['xUserPassword']);
        }

        if (requestParameters['xUserEmail'] != null) {
            headerParameters['X-User-Email'] = String(requestParameters['xUserEmail']);
        }

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("API_Key", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }
        const response = await this.request({
            path: `/user/id/{id}/project`.replace(`{${"id"}}`, encodeURIComponent(String(requestParameters['id']))),
            method: 'PUT',
            headers: headerParameters,
            query: queryParameters,
            body: LinkProjectModelToJSON(requestParameters['linkProjectModel']),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => UserResponseFromJSON(jsonValue));
    }

    /**
     * Associates a user with a project ID.
     * Link user to project.
     */
    async userControllerLinkUserWithProjectId(requestParameters: UserControllerLinkUserWithProjectIdRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<UserResponse> {
        const response = await this.userControllerLinkUserWithProjectIdRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Updates the user type for an existing user. User type can be thought of as a role with role-based permissions, e.g. SUPERADMIN could have permissions an ADMIN would not. Only SUPERADMIN users can set types
     * Update user type.
     */
    async userControllerSetUserTypeRaw(requestParameters: UserControllerSetUserTypeRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<UserResponse>> {
        if (requestParameters['setUserTypeModel'] == null) {
            throw new runtime.RequiredError(
                'setUserTypeModel',
                'Required parameter "setUserTypeModel" was null or undefined when calling userControllerSetUserType().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (requestParameters['xUserPassword'] != null) {
            headerParameters['X-User-Password'] = String(requestParameters['xUserPassword']);
        }

        if (requestParameters['xUserEmail'] != null) {
            headerParameters['X-User-Email'] = String(requestParameters['xUserEmail']);
        }

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("API_Key", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }
        const response = await this.request({
            path: `/user/type`,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: SetUserTypeModelToJSON(requestParameters['setUserTypeModel']),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => UserResponseFromJSON(jsonValue));
    }

    /**
     * Updates the user type for an existing user. User type can be thought of as a role with role-based permissions, e.g. SUPERADMIN could have permissions an ADMIN would not. Only SUPERADMIN users can set types
     * Update user type.
     */
    async userControllerSetUserType(requestParameters: UserControllerSetUserTypeRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<UserResponse | null | undefined > {
        const response = await this.userControllerSetUserTypeRaw(requestParameters, initOverrides);
        switch (response.raw.status) {
            case 200:
                return await response.value();
            case 201:
                return null;
            default:
                return await response.value();
        }
    }

    /**
     * Removes a user from a project.
     * Unlink user from project.
     */
    async userControllerUnlinkUserFromProjectRaw(requestParameters: UserControllerUnlinkUserFromProjectRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<UserResponse>> {
        if (requestParameters['id'] == null) {
            throw new runtime.RequiredError(
                'id',
                'Required parameter "id" was null or undefined when calling userControllerUnlinkUserFromProject().'
            );
        }

        if (requestParameters['unlinkProjectModel'] == null) {
            throw new runtime.RequiredError(
                'unlinkProjectModel',
                'Required parameter "unlinkProjectModel" was null or undefined when calling userControllerUnlinkUserFromProject().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (requestParameters['xUserPassword'] != null) {
            headerParameters['X-User-Password'] = String(requestParameters['xUserPassword']);
        }

        if (requestParameters['xUserEmail'] != null) {
            headerParameters['X-User-Email'] = String(requestParameters['xUserEmail']);
        }

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("API_Key", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }
        const response = await this.request({
            path: `/user/id/{id}/project`.replace(`{${"id"}}`, encodeURIComponent(String(requestParameters['id']))),
            method: 'DELETE',
            headers: headerParameters,
            query: queryParameters,
            body: UnlinkProjectModelToJSON(requestParameters['unlinkProjectModel']),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => UserResponseFromJSON(jsonValue));
    }

    /**
     * Removes a user from a project.
     * Unlink user from project.
     */
    async userControllerUnlinkUserFromProject(requestParameters: UserControllerUnlinkUserFromProjectRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<UserResponse> {
        const response = await this.userControllerUnlinkUserFromProjectRaw(requestParameters, initOverrides);
        return await response.value();
    }

}
